### ISSUE TITLE
Examples do not seem to work in Safari or Firefox

### ISSUE THREAD

**Issue by justindavies** [vasturiano/force-graph#1]
On the console I keep getting:

[Error] Unhandled Promise Rejection: TypeError: The provided value is non-finite
	getImageData (force-graph.min.js:2:96999)
	e (force-graph.min.js:2:96999)
	init (force-graph.min.js:2:97459)
	n (force-graph.min.js:2:44363)
	i (force-graph.min.js:2:44325)
	(anonymous function) (directional-links:13)
	promiseReactionJob

Which relates to:
var t = o.colorTracker.lookup(u.getImageData(s.x, s.y, 1, 1).data);

Looking at the code, it seems to check if pointer interaction is enabled, but even if I disable it, I still get the exception.

**Comment by vasturiano** [comment]
Thanks for the report @justindavies. There were some browser incompatibility issues causing the error. Should be fixed now.
