### ISSUE TITLE
Nodes of different sizes

### ISSUE THREAD

**Issue by Flashfyre** [vasturiano/force-graph#101]
Would it be possible to implement a way to make node size rely on a function with the node object as its parameter? I can simply draw nodes bigger, but this doesn't help me with collision detected through the d3Force function as that function has no node argument.

**Comment by Flashfyre** [comment]
I was able to find in the d3 source that you can pass a function into d3.forceCollide, so this mostly solves my issue, but I believe there are other functions that use nodeRelSize and it would be nice to be able to specify a function for that in one place to use everywhere.

**Comment by vasturiano** [comment]
@Flashfyre the method you're looking for is `nodeVal`, which affects the size of nodes individually. So you can do `myGraph.nodeVal(node => <your code>)`.

And yes, if you're using `forceCollide` you can use the `radius` method to specify the nodes' radii.

**Comment by Flashfyre** [comment]
Thanks, that should do it.
