### ISSUE TITLE
dag-yarn example not working correctly in reactJS

### ISSUE THREAD

**Issue by maximegheraille** [vasturiano/force-graph#102]
**Describe the bug**
I used the index from dag-yarn with my own data and it works perfectly, but when using the same data and the same graph options in my react app, I get all the children of my nodes on each other.
**Expected behavior**
I should have the same behaviour in react as in the index

**Screenshots**
<img width="1219" alt="Screenshot 2020-03-02 at 14 27 06" src="https://user-images.githubusercontent.com/32335849/75680499-09f12280-5c92-11ea-8a1f-9d0aed521a79.png">
<img width="847" alt="Screenshot 2020-03-02 at 14 25 48" src="https://user-images.githubusercontent.com/32335849/75680503-0d84a980-5c92-11ea-872b-3a8b78469af4.png">
<img width="1219" alt="Screenshot 2020-03-02 at 14 26 52" src="https://user-images.githubusercontent.com/32335849/75680502-0cec1300-5c92-11ea-93ac-bb420684dd40.png">
<img width="847" alt="Screenshot 2020-03-02 at 14 25 34" src="https://user-images.githubusercontent.com/32335849/75680507-0e1d4000-5c92-11ea-97b6-f715263dd487.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by vasturiano** [comment]
@maximegheraille could you please make a reproduceable example on https://codesandbox.io/ so it can be debugged further?

**Comment by maximegheraille** [comment]
@vasturiano here is the codesandbox https://codesandbox.io/s/silly-sea-4r6ro?fontsize=14&hidenavigation=1&theme=dark

**Comment by vasturiano** [comment]
@maximegheraille the issue appears to be that the invocation of the `d3Force` method is incorrect. This is a component method, not a property, therefore your instruction on L129 has no effect:
```
d3Force={("collide", d3.forceCollide(30))}
```

You should call `d3Force` as method, using a `ref` to your graph. Please see the below example for usage:
https://github.com/vasturiano/react-force-graph/blob/master/example/tree/index.html#L43

**Comment by maximegheraille** [comment]
@vasturiano thank you, it worked perfectly ! 
here is the updated version for people having the same problem
https://codesandbox.io/s/cocky-liskov-f3g23?fontsize=14&hidenavigation=1&theme=dark
