### ISSUE TITLE
start with an open PrunedTree instead of closed 

### ISSUE THREAD

**Issue by maximegheraille** [vasturiano/force-graph#103]
**Is your feature request related to a problem? Please describe.**
it would be nice to be able to get the graph fully open  on load and be able to close nodes.
Now we have to start with all nodes closed and open them one by one.
https://codesandbox.io/s/purple-fog-hmi2p?fontsize=14&hidenavigation=1&theme=dark

**Comment by vasturiano** [comment]
@maximegheraille you should be able to define the initial state of your tree by setting the appropriate `collapsed` values. For example, all set to `false` if you want the tree to start fully expanded.

**Comment by maximegheraille** [comment]
@vasturiano just got It working when adding 'node.collapsed = false;' in my foreach inside the function nodesById. 

Is there a way to prevent to whole graph from reloading and only reload the collapsed node ? ( now it looks weird because it reloads the whole graph and doesn't keep them in the same place it was before collapsing) 

https://codesandbox.io/s/optimistic-kapitsa-1rq7y?fontsize=14&hidenavigation=1&theme=dark

**Comment by maximegheraille** [comment]
@vasturiano just got It working when adding 'node.collapsed = false;' in my foreach inside the function nodesById.

https://codesandbox.io/s/optimistic-kapitsa-1rq7y?fontsize=14&hidenavigation=1&theme=dark
