### ISSUE TITLE
Export graph to svg

### ISSUE THREAD

**Issue by pournaki** [vasturiano/force-graph#104]
Hello,
I am wondering what would be the easiest solution to export and save a created graph as .svg from within the browser. Is there a straightforward way to do this? 
Thanks a lot for your help!

**Comment by vasturiano** [comment]
@pournaki thanks for reaching out. 

The library is rendering to `canvas`, so conversion to `svg` is not going to be trivial. But, you could potentially export the raster data to a `jpg`/`png` using [canvas.toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).

**Comment by pournaki** [comment]
@vasturiano thanks for your quick reply! It works fine with the suggested canvas.toDataURL. The resolution is not very high, but I guess it's as good as it gets. Thanks!

**Comment by gkorland** [comment]
@vasturiano Did you a good solution that allows export as SVG or better resolution?

**Comment by vasturiano** [comment]
@gkorland export to SVG, I don't really see how that would be doable given that the representation is in raster.

But you can increase the resolution of your image simply by making your canvas larger, using the `width` and `height` props.
