### ISSUE TITLE
combine "text as nodes" and "click"

### ISSUE THREAD

**Issue by smartsl** [vasturiano/force-graph#11]
while using these together:
.nodeCanvasObject()
.onNodeClick(),
only small center of the canvas can trigger click event, not entire object.

**Comment by vasturiano** [comment]
Thanks @smartsl. 

When using `nodeCanvasObject` to generate custom shapes, the 'hover' (and click) area of the nodes is still defined as a circle (invisible) around the central point of the node. The reason for this is that a shadow (invisible) canvas is used to detect pointer interactions, and objects are detected according to their own unique custom color, set by the lib using [canvas-color-tracker](https://github.com/vasturiano/canvas-color-tracker). If you are defining your own shapes, the framework can't control the node colors, therefore why it falls back to using standard circles.

So, the way that you can control the node interaction area is by setting the methods `nodeRelSize` and `nodeVal`. This will define the radius of the circle hover area. 

Let me know if this approach works for you.
