### ISSUE TITLE
Stop animation during node add, remove or drag method

### ISSUE THREAD

**Issue by ravik3592** [vasturiano/force-graph#115]
I have defined function to add and remove node, but after adding or removing, the graph keeps on moving slowly, is there any way to stop this animation during add and remove.
In dagmode this causes more issue compared to forced mode. , i have applied d3force(center, null) but no difference in that

**Comment by vasturiano** [comment]
@ravik3592 everytime you changed the data structure, either by removing or adding nodes, you should let the graph adjust to the changes so it finds the new layout balance.

If you really don't wish that to happen, you can cancel the force directed engine effect by setting `.cooldownTicks(0)`. 
But keep in mind that new nodes will be added to the center of the canvas and not move.

**Comment by ravik3592** [comment]
Thanks @vasturiano . It helped a lot,
 is there option to select nodes and move in group, after i set cooldownticks(0). only one node gets moved, its connected nodes are not moving, can i select connected nodes and move as a group?

**Comment by vasturiano** [comment]
@ravik3592 there is an example on the twin repo [3d-force-graph](https://github.com/vasturiano/3d-force-graph) that you can adapt to select multiple nodes using modifier keys, and drag them as a group.

The [example](https://vasturiano.github.io/3d-force-graph/example/multi-selection/) source is here: https://github.com/vasturiano/3d-force-graph/blob/master/example/multi-selection/index.html#L31-L55

**Comment by ravik3592** [comment]
okay i will try this approach in my graph, since im not using 3d graph.

**Comment by ravik3592** [comment]
@vasturiano I tried to applied the same logic but im not able to get thorugh it. 
is it possible to write a snippet for forced graph without 3d to support multiselect

**Comment by vasturiano** [comment]
@ravik3592 just added an example to the repo. Please see here:
https://vasturiano.github.io/force-graph/example/multi-selection/
https://github.com/vasturiano/force-graph/blob/master/example/multi-selection/index.html

**Comment by ravik3592** [comment]
TypeError: Cannot read property 'x' of undefined. in the below line.
            .forEach(node => ['x', 'y'].forEach(coord => node[`f${coord}`] = node[coord] + translate[coord])); // translate other nodes by same amount.

Node Object:
id: "{E4061F96-4CE7-49b4-9E96-46A353804BD8}"
col: "#8b2836"
name: "Download as Image"
guid: "{E4061F96-4CE7-49b4-9E96-46A353804BD8}"
eaType: "UseCase"
eaStereotype: "usecase"
eafqName: null
eaTechnology: "Prolaborate"
eaProperties: null
isEnabled: true
__indexColor: "#c00010"
index: 15
x: -194.08321453382567
y: -312.33694029049354
vx: 0
vy: 0
fx: -194.08321453382567
fy: -312.33694029049354
isClicked: true


Selected Set:
[[Entries]]
0:
value:
id: "{9F3C6C86-7F53-4ff6-80AC-0F583C22E0E8}"
col: "#8b2836"
name: "Edit Diagrammer Views"
guid: "{9F3C6C86-7F53-4ff6-80AC-0F583C22E0E8}"
eaType: "UseCase"
eaStereotype: "usecase"
eafqName: null
eaTechnology: "Prolaborate"
eaProperties: null
isEnabled: true
__indexColor: "#24000b"
index: 10
x: 211.8185580884519
y: -291.1078809225376
vx:
4.707690271401148
e-10
vy:
-7.192543490611941
e-10
fx: undefined
fy: undefined
isClicked: false

**Comment by vasturiano** [comment]
@ravik3592 are you seeing that error in the example link I posted:
https://vasturiano.github.io/force-graph/example/multi-selection/

**Comment by ravik3592** [comment]
@vasturiano group selection worked after i updated my force graph version. i was using older version which caused the issue.
But when i set .cooldownTicks(0) this group selection and drag not working. i tried with the example in above link also.

**Comment by vasturiano** [comment]
@ravik3592 I see. If you set `.cooldownTicks(0)` the `f*` attributes don't have the chance to be propagated to the real attributes (because that happens during an engine tick).
So for that particular case I would suggest to assign the new coords also to the x,y attributes.

So, extend:
```js
.forEach(node => ['x', 'y'].forEach(coord => node[`f${coord}`] = node[coord] + translate[coord]));
```

with

```js
.forEach(node => ['x', 'y'].forEach(coord => node[coord] = node[`f${coord}`] = node[coord] + translate[coord]));
```

**Comment by ravik3592** [comment]
yes this worked..thanks.
