### ISSUE TITLE
Dynamically Update linkDirectionalParticles

### ISSUE THREAD

**Issue by RayyanRiaz** [vasturiano/force-graph#116]
Hi,
Firstly, thanks for such a great library that has mitigated the performance issues of D3Js to a great extent. 
I have a graph where links have multiple numerical properties. I am trying to update the `linkDirectionalParticles` based upon the selected link property but it does not work as expected.

**To Reproduce**
```
ForceGraph()
...
.linkDirectionalParticles(variableToSelectSpecificNumericalPropertyOfEdge)

```
-----
The behavior persists when I use `linkDirectionalArrowLength(.)` as:
`.linkDirectionalParticles(l => l[variableToSelectSpecificNumericalPropertyOfEdge])
`

*Example*:

suppose the graph has just two nodes and a link, with two properties: `flow1=5` and `flow2=10`. Now, if user has chosen to view `flow1`, the emitted particles should be `5`. When `flow2` is selected, the emitted particles should be `10`, without changing the state of force layout.

**Expected behavior**
Ideally, the number of `linkDirectionalParticles` should be updated dynamically as the value of variable gets updated, while keeping the rest of graph state intact.

**Comment by RayyanRiaz** [comment]
The simple example is given below

```
<!DOCTYPE html>
<html>
<body>
    <div id="network"></div>
    <script src="https://unpkg.com/force-graph"></script>
    <script type="text/javascript">
      let graph = {
        nodes: [{ id: 1 }, { id: 2 }],
        links: [{ source: 1, target: 2, flow1: 5, flow2: 10 }]
      };
      let edgeWeightType = "flow1";
      ForceGraph()(document.getElementById("network"))
        .graphData(graph)
        .linkDirectionalParticles(l => l[edgeWeightType]);

      setTimeout(() => {
        edgeWeightType = "flow2";
      }, 5000);
    </script>
  </body>
</html>
```

**Comment by vasturiano** [comment]
@RayyanRiaz thanks for reaching out. 

To induce a change, you have to re-call the `.linkDirectionalParticles` method. Otherwise the graph has no way to know you've changed that logic. For your purpose you can also just do `.linkDirectionalParticles(edgeWeightType)`, it's a short hand for the same behaviour.

So, in your script:

```js
      const graphData = {
        nodes: [{ id: 1 }, { id: 2 }],
        links: [{ source: 1, target: 2, flow1: 5, flow2: 10 }]
      };

      const myGraph = ForceGraph()(document.getElementById("network"))
        .graphData(graphData)
        .linkDirectionalParticles('flow1');

      setTimeout(() => {
        myGraph.linkDirectionalParticles('flow2');
      }, 5000);
```

**Comment by RayyanRiaz** [comment]
Aah, right! Thanks a lot for quick reply :) It works the way you mentioned.
