### ISSUE TITLE
TypeScript definition for nodeCanvasObjectMode(...) is too strict.

### ISSUE THREAD

**Issue by martin-cowie** [vasturiano/force-graph#123]
**Describe the bug**
Type signature `nodeCanvasObjectMode(modeAccessor: string | ((obj: NodeObject) => CanvasCustomRenderMode))` conflicts with docs & effective use.

**To Reproduce**
This code is reasonable, 

```
        this.forceGraph = ForceGraph()(graphElem)
            .nodeCanvasObjectMode((node) => someBoolean ? "replace" : "default" )
```

but `tsc` cannot compile it, stating:
```
Argument of type '(node: NodeObject) => "replace" | "default"' is not assignable to parameter of type 'string | ((obj: NodeObject) => CanvasCustomRenderMode)
```

as `default` is not in the enumeration:

```
type CanvasCustomRenderMode = 'replace' | 'before' | 'after';
```

The docs for this method state `Any other value will be ignored and the default drawing will be applied`, the definition of `nodeCanvasObjectMode` however forbids returning any other value.

**Solutions**

Pragmatically you could extend the definition of `nodeCanvasObjectMode(...)` to expect a `CanvasCustomRenderMode|string` or add `default` to `CanvasCustomRenderMode`. 

More radically, change the behaviour of nodeCanvasObjectMode to expect either a returned `CanvasCustomRenderMode|null`, where `null` explicitly signals default behaviour.

**Comment by vasturiano** [comment]
@martin-cowie thanks for reaching out. You bring up a good point.

I'm thinking you should be able to use `null` to indicate the default behavior, instead of the `default` string. Something like:
```js
.nodeCanvasObjectMode((node) => someBoolean ? "replace" : null)
```

Let me know if that solves your TS compatibility issue.

**Comment by martin-cowie** [comment]
This works for me Vasco.

**Comment by martin-cowie** [comment]
Morning Vasco. For my own purposes, can we close this ticket when there's a git commit hash for me to pull?
