### ISSUE TITLE
automatically get graph zoomed out to fit the screen

### ISSUE THREAD

**Issue by maximegheraille** [vasturiano/force-graph#124]
**Is your feature request related to a problem? Please describe.**

Yes, my graph is never fully visible after loading, some part are always hidden because the graph is larger then the screen, even if i change the the zoom and centerAt options, it will never work correctly depending on the given data structure

**Describe the solution you'd like**

I have no idea if there is a way with the graph and tsx to get the grap zoomed out and fit the screen

**Comment by vasturiano** [comment]
Thanks for your request @maximegheraille.

I've just added a convenience method that makes this easy to do:
```js
myGraph.zoomToFit(<transition time>, <padding>)
``` 

As used in [this example](https://vasturiano.github.io/force-graph/example/fit-to-canvas/), you can invoke that after the engine has stopped, for instance:
```js
Graph.onEngineStop(() => Graph.zoomToFit(400));
```
