### ISSUE TITLE
Include link weights

### ISSUE THREAD

**Issue by pournaki** [vasturiano/force-graph#126]
I wonder if it is possible to include link weights in the calculations for the force-directed algorithm, such that links with higher weights have a higher contribution to the attraction between their nodes.

**Comment by vasturiano** [comment]
@pournaki you can configure either the `distance` or `strength` parameter of the [link force](https://github.com/d3/d3-force#link_distance) to behave the way you're describing.

Those methods accept a link accessor function, so if you have weights associated to your link objects you can do something like:
```js
myGraph.d3Force('link').distance(link => /* your logic based on the link weight */)
```

**Comment by pournaki** [comment]
This is great, thank you very much!
