### ISSUE TITLE
Performance on mobile

### ISSUE THREAD

**Issue by szamok** [vasturiano/force-graph#134]
This is the 2D version of https://github.com/vasturiano/3d-force-graph/issues/342.

The setup of my 2D version of my scene looks like this way:
`        const maxIdx = 1406;
        let materials = {}

        function loadTextures() {
            for (let t = 0; t <= maxIdx / 256; t++) {
                const img = new Image();
                img.src = '/images/galaxy/' + t + ((t + 1) * 256 < maxIdx ? '.jpg' : '.jpg?uid=' + maxIdx);
                materials[t] = img;
            }
        }

        function showGalaxy() {
            jQuery('#instr').hide();
            jQuery('#galaxy').show();
            jQuery('body').css({ 'background-image': 'none' });
            jQuery('body').css({ 'background-color': '#000'});
            prepareGalaxy();
        }

        function prepareGalaxy() {
            fetch('/galaxy/galaxy.json?last=' + maxIdx).then(res => res.json()).then(data => {
                const graph = ForceGraph({ controlType: 'fly' })
                    (document.getElementById('galaxy'))
                    .graphData(data)
                    .linkVisibility(link => Number.isInteger(link.target))
                    .nodeCanvasObject((node, ctx, globalScale) => {
                        if (node.type == "C") {
                            const label = node.text;
                            const fontSize = 12 / globalScale;
                            ctx.font = `${fontSize}px Sans-Serif`;
                            const textWidth = ctx.measureText(label).width;
                            const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding

                            ctx.textAlign = 'center';
                            ctx.textBaseline = 'middle';
                            ctx.fillStyle = '#fff';
                            ctx.fillText(label, node.x, node.y);
                        }
                        else {
                            let size = 30 + node.r * 3;
                            let img = materials[node.i];

                            let sx = Math.floor(node.u * 4096);
                            let sy = Math.floor(node.v * 4096);
                            let sw = Math.floor(node.w * 4096);
                            let sh = Math.floor(node.h * 4096);
                            ctx.drawImage(img, sx, sy, sw, sh, Math.floor(node.x - size / 2), Math.floor(node.y - size / 2), size, size);
                            //console.log(node.x);
                        }
                    })
                    .onNodeClick((node, e) => {
                        window.open(webroot + node.id + '/' + node.t);
                    })
                    ;
                graph.d3Force('link').distance((d) => {
                    if (d.source.type === "C") {
                        return 800;
                    }
                    return 200;
                }).strength(1)
            });
        }

        loadTextures();
`

This works on a quite fast mobile phone, but it's very slow. Same huge 4096x4096 images are used as in the 3D version and 256x256 pixel parts of the huge images are drawn for all 1500 nodes.
When I draw no images (or fragment of them) then it's much faster.
Should I use some other method to draw the images or should I reduce the number of nodes?
Thank you.

**Comment by vasturiano** [comment]
@szamok depending on how many nodes you have in your system, probably rendering 4k images is what's putting the strain on the cpu.
In canvas, the higher the resolution of an image the more work the canvas renderer need to do to light those pixels. And due to the frame engine is repainting every single image at every frame, making it difficult to maintain a 60 fps.

I would try first decreasing the resolution of your images. Let me know if that helps.

**Comment by szamok** [comment]
@vasturiano 
To correctly understand your idea, let me explain more details.

I have around 1500 nodes (can be more in the future), each one has a different image assigned. The size of each image is 256x256. So there are 6 4096x4096 images with 256x256 tiles, so one huge images contains images for 16x16 = 256 nodes (except for the last one). I use context.drawImage with the right coordinates to split the right 256x256 segment from the huge image for each node.

I wouldn't reduce the 256x256 image size/resolution (128x128 or similar) since the text written on the images would become unreadable, and the original images are already several times larger as the 256x256 is already the downscaled version.

So can the problem be that I split the required 256x256 image fragment from the large 4096x4096 image via drawImage? Would it be better to have smaller huge images (like 2048x2048 or 1024x1024) containing the small images? Whould it be even better to split the huge images to small one (somehow on the client side) before using them?
Thank you,

**Comment by vasturiano** [comment]
@szamok thanks for the explanation. It could well be that the (repeated) cropping of the original 4k image using `drawImage` is adding a performance penalty compared to having the images already split and ready to draw. 

I would experiment with this approach to see if you get an improvement in performance. For convenience, you can split the images client side (on your `loadTextures` method for example) and have them ready to be drawn individually in the `nodeCanvasObject` method.

Generally speaking, you want to have the `nodeCanvasObject` method do the least possible, because it is called extremely frequently (once per node per frame). So anything you can pre-process / cache ahead of time helps.

**Comment by szamok** [comment]
@vasturiano

Thank you for the hint splitting the images in advance. It's several times faster and now it's usable.

According to your advice, in the loadTextures I download&wait all huge images, split them, and put all into a dictionary. The nodeCanvasObject just draws the images to the right place with the right size. 
`
        $('#start').prop('disabled', true);

        const maxIdx = 1422;
        let images = {}
        let materials = {}
        let cnt = 0;

        function loadTextures() {
            cnt = maxIdx / 256;
            for (let t = 0; t <= maxIdx / 256; t++) {
                const img = new Image();
                img.onload = function () {
                    cnt--;
                    if (cnt <= 0) {
                        splitImages();
                    }
                };
                img.src = '/images/galaxy/' + t + ((t + 1) * 256 < maxIdx ? '.jpg' : '.jpg?uid=' + maxIdx);
                materials[t] = img;
            }
        }

        function splitImages() {
            fetch('/galaxy/galaxy.json?last=' + maxIdx).then(res => res.json()).then(data => {
                galaxyData = data;

                for (node of galaxyData.nodes) {
                    if (node.type == 'C') {
                        continue;
                    }
                    let canvas = document.createElement('canvas');
                    let ctx = canvas.getContext('2d');
                    let mat = materials[node.i];

                    let sx = Math.floor(node.u * 4096);
                    let sy = Math.floor(node.v * 4096);
                    let sw = Math.floor(node.w * 4096);
                    let sh = Math.floor(node.h * 4096);

                    canvas.width = sw;
                    canvas.height = sh;
                    ctx.drawImage(mat, sx, sy, sw, sh, 0, 0, sw, sh);

                    let img = new Image();
                    img.src = canvas.toDataURL();
                    images[node.id] = img;
                    canvas.remove();
                }

                $('#loading').hide();
                $('#start').prop('disabled', false);
            });
        }

        function showGalaxy() {
            jQuery('#instr').hide();
            jQuery('#galaxy').show();
            jQuery('body').css({ 'background-image': 'none' });
            jQuery('body').css({ 'background-color': '#000'});
            prepareGalaxy();
        }

        function prepareGalaxy() {
            const graph = ForceGraph({ controlType: 'fly' })
                (document.getElementById('galaxy'))
                .graphData(galaxyData)
                .linkVisibility(link => Number.isInteger(link.target))
                .nodeCanvasObject((node, ctx, globalScale) => {
                    if (node.type == "C") {
                        const label = node.text;
                        const fontSize = 12 / globalScale;
                        ctx.font = `${fontSize}px Sans-Serif`;
                        const textWidth = ctx.measureText(label).width;
                        const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding

                        ctx.textAlign = 'center';
                        ctx.textBaseline = 'middle';
                        ctx.fillStyle = '#fff';
                        ctx.fillText(label, node.x, node.y);
                    }
                    else {
                        let size = 30 + node.r * 3;
                        let img = images[node.id];

                        let sw = size * Math.floor(node.w * 4096) / 256;
                        let sh = size * Math.floor(node.h * 4096) / 256;
                        ctx.drawImage(img, node.x - sw / 2, node.y - sh / 2, sw, sh);
                    }
                })
                .nodeRelSize(30)
                .onNodeClick((node, e) => {
                    window.open(webroot + node.id + '/' + node.t);
                })
                ;
            graph.d3Force('link').distance((d) => {
                if (d.source.type === "C") {
                    return 800;
                }
                return 200;
            }).strength(1);
        }

        loadTextures();
`
