### ISSUE TITLE
how to use force-graph to show node attributes and relationship attributes

### ISSUE THREAD

**Issue by minicloudsky** [vasturiano/force-graph#135]
how to use force-graph to show node attributes and relationship attributes , such as the demo as the below .
in my view, I should bind onNodeHover(fn)  and onLinkHover(fn) ,any ideas is welcomed，thanks in advance.
https://eisman.github.io/neo4jd3/

**Comment by vasturiano** [comment]
@minicloudsky yes, you can use those methods to extract and show additional information on the nodes/links being hovered.

**Comment by minicloudsky** [comment]
thank you very much, besides, how can i add a line with arrow between the two nodes ,so that i can add additional attributes on the line，thanks .

**Comment by vasturiano** [comment]
@minicloudsky look into the `linkDirectionalArrow` methods. It should do what you need. 
Here's an example: https://vasturiano.github.io/force-graph/example/directional-links-arrows/
