### ISSUE TITLE
How to display data on circular nodes and directed line segments of node relationship?

### ISSUE THREAD

**Issue by minicloudsky** [vasturiano/force-graph#136]
I need to show data on the circle node and show data on the line between two nodes, what should i do ,thank you very much .

**Comment by vasturiano** [comment]
For custom node/link representation, you should use the `nodeCanvasObject` and `linkCanvasObject` methods respectively.

You find some usage examples on the main repo readme:
https://vasturiano.github.io/force-graph/example/text-nodes/
https://vasturiano.github.io/force-graph/example/text-links/
https://vasturiano.github.io/force-graph/example/img-nodes/

**Comment by minicloudsky** [comment]
thank you very much , i got it.
