### ISSUE TITLE
Remove console.info

### ISSUE THREAD

**Issue by hornta** [vasturiano/force-graph#138]
My console is getting spammed with `force-graph loading 2 nodes 1 links`. It should not be in production code.
https://github.com/vasturiano/force-graph/blob/3cf39624cd3d7566bc8fc56e877461a3b35b7f46/src/force-graph.js#L128

**Comment by VitaliiHoncharenko** [comment]
any updates?

**Comment by vasturiano** [comment]
The console info was removed, starting from version `1.40.1`.
