### ISSUE TITLE
Is it possible to generate the nodes colser, even though graph is big

### ISSUE THREAD

**Issue by manu-058** [vasturiano/force-graph#142]
**Describe the bug**
Is it possible to generate the nodes colser, even though graph is big
**To Reproduce**
Below is the image of of a graph, as you can see there is lot of empty space, 
so is it possible to generate nodes colser , so that i can avoid those empty spaces.
i am using zoomToFit
![Screenshot (490)](https://user-images.githubusercontent.com/38914354/93122898-ea2cc380-f6e4-11ea-988f-0cd097076de0.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : chrome,
 - Version : 1.33.1

Thank you

**Comment by iviv62** [comment]
Yes, there is an option to change the distance of the links using the d3Force(str, [fn]) function.
If that is what you want.
You can use it like this...

.d3Force('link', d3.forceLink(links).distance(value))

where the variable links is the array with your links
and value is some number.You can read more about it here: 
https://github.com/d3/d3-force#forceLink

**Comment by manu-058** [comment]
@iviv62 Thanks you,
I tried the below code , but it giving the error, could you please let me know where i am going wrong,
  
  
```
 const LINKS = [
      {"source": "Alice", "target": "Bob"},
      {"source": "Bob", "target": "Carol"}
    ];
const NODES = [
      {"id": "Alice"},
      {"id": "Bob"},
      {"id": "Carol"}
    ];

    this.elem = document.getElementById('graph');
    this.Graph = ForceGraph()(this.elem)
      .graphData({ nodes: NODES, links: LINKS })
      .d3Force('collide', d3.forceCollide(8))
      .d3Force('link', d3.forceLink(LINKS).distance(100))
      ; 
```
```
core.js:4002 ERROR Error: node not found: Alice
    at c (d3-force:2)
    at g (d3-force:2)
    at Function.x.initialize (d3-force:2)
    at initializeForce (force-graph.js:8251)
    at Object.force (force-graph.js:8299)
    at Function.d3Force (force-graph.js:11287)
    at Function.comp.<computed> [as d3Force] (force-graph.js:5169)
    at force-graph.js:11749
    at Array.forEach (<anonymous>)
    at Function.<anonymous> (force-graph.js:11747)
```

```
Below are the script tags i am using
  <script src="//unpkg.com/force-graph"></script>

  <script src="//unpkg.com/d3-quadtree"></script>

  <script src="//unpkg.com/d3-force"></script>
```

**Comment by iviv62** [comment]
Oh. Ok in your case leave it like this
.d3Force('link', d3.forceLink().distance(100))

and it must work!

**Comment by manu-058** [comment]
thanks @iviv62  that worked,

although when i tried to implments for the larger graph it is still taking too much space in the screen,
https://stackblitz.com/edit/angular-pby1y5-7pfkah?file=src/app/card-overview-example.ts (click on it to see implmentation)

So i tred   Deactivateing  existing forces using
`      .d3Force('charge', null)`
this time it became too cluttered
https://stackblitz.com/edit/angular-pby1y5-wub1hh?file=src/app/card-overview-example.ts (click on it to see implmentation)

so if there was a way to reduce this clutteredness it would be helpful.

**Comment by wunaidage** [comment]
you can even count the child node of a specific node and then assign a specific link force the that link
