### ISSUE TITLE
Is it possible not to display nodes which does not have any link

### ISSUE THREAD

**Issue by manu-058** [vasturiano/force-graph#143]
**Describe the bug**
Is it possible not to display nodes which does not have any link

![Screenshot (496)](https://user-images.githubusercontent.com/38914354/93267740-c1cac500-f7c9-11ea-8d06-cceac228bdae.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser :chrome,
 - Version : latest

Thank you

**Comment by Alexithemia** [comment]
```
.nodeVisibility((node) => {
  links = graph.graphData().links;
  return links.find(link => link.source.id === node.id || link.target.id === node.id);
})
```

Should work. Not sure how performant it would be. You may just want to parse it once before graphing.

```
const data = {
  nodes: [ ... ],
  links: [ ... ]
}

data.nodes.forEach(node => {
  data.links.ForEach(link => {
    if (link.source.id === node.id || link.target.id === node.id) {
      node.hasLink = true;
    }
  }
}

// then add this to your graph
.nodeVisibility((node) => {
  return node.hasLink;
})
```

**Comment by manu-058** [comment]
thanks @Alexithemia  that worked.

**Comment by Alexithemia** [comment]
@manu-058 This actually may be the best option and most performant

```
.nodeVisibility((node) => {
  if (graph.linkSource([node.id] || graph.linkTarget([node.id])) {
    return true;
  }
  return false;
}
```
