### ISSUE TITLE
Group hull drawing issue

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/force-graph#144]
@vasturiano I talked to you awhile back about drawing hulls for groups of nodes I create, and you suggested having it draw the hulls with the first node in the .nodeCanvasObject with `if (node === nodes[1]) ` but it of course does not hit this node and draw if it is hidden. Is there another way to trigger this or could you include a method to draw something first every draw cycle? 

Maybe allow options to draw before links & nodes, between links & nodes, and after both.

**Comment by vasturiano** [comment]
@Alexithemia good question. Maybe we could have a `.onRenderFrame(ctx => ...)` type of callback method that allows you to hook into the render engine at every frame.
This would make that functionality more apparent.
Not sure whether we need to have one for pre node/link render and another for post, or if we could just live with one of them.

**Comment by Alexithemia** [comment]
It would really depend on what you need to draw, being able to say when you want to hook in would allow a lot of customization. For my use case, I want to draw hulls before links so the hulls do not cover them. I currently have to make the hulls semi-transparent to see them.

Other use cases may want to cover links or somehow add something to them by drawing after them, but still under nodes. 

Some people may need to draw something on top of everything like a custom pop up or animation etc.

**Comment by vasturiano** [comment]
Ok, I think you make a good case for having both.
So, maybe we'll add two methods: 
```js
.onRenderFrameStart(ctx => ...)
.onRenderFrameEnd(ctx => ...)
```

**Comment by vasturiano** [comment]
@Alexithemia these methods have now been added on the latest version (`1.34.0`).

https://github.com/vasturiano/force-graph#render-control

Please try it and let me know if it works fine for you.
