### ISSUE TITLE
programmatically click on a node/link

### ISSUE THREAD

**Issue by DekelZoaretz** [vasturiano/force-graph#146]
This is a great project!
I want to be able to select a node as if I clicked on it. 
Is there a way from this library to achieve it?

**Comment by vasturiano** [comment]
@DekelZoaretz did you try `onNodeClick()`?

**Comment by DekelZoaretz** [comment]
@vasturiano thank you for the quick response.
isn't `onNodeClick()` just a listener function?
I have the node id and I want to perform a click on it as if the user clicked on it?
How can I do it with only `onNodeClick()` ?

**Comment by DekelZoaretz** [comment]
@vasturiano thank you very much.
I solved it by calling the callback function that inside the `onNodeClick(callback)`
