### ISSUE TITLE
Can I place node on graph without affecting existing node?

### ISSUE THREAD

**Issue by wunaidage** [vasturiano/force-graph#147]
Hi I want to place the nodes that don't have any links to the bottom of the canvas and list them like from left to right and hope it does not affect others. is it possible?

**Comment by vasturiano** [comment]
@wunaidage you can always set custom positions for your nodes using `fx` and `fy` attributes on the node objects.

**Comment by wunaidage** [comment]
will the charge push other nodes away?

**Comment by vasturiano** [comment]
Yes, as mentioned in the docs there is a [forceManyBody](https://github.com/d3/d3-force#forceManyBody) repelling force that is pushing all the nodes apart. You can access this force with `myGraph.d3Force('charge')`.
