### ISSUE TITLE
random is not a function error

### ISSUE THREAD

**Issue by wunaidage** [vasturiano/force-graph#149]
I encounter this error: 

ERROR TypeError: random is not a function
    at jiggle.js:2
    at apply (manyBody.js:81)
    at Quadtree.visit (visit.js:7)
    at force (manyBody.js:19)
    at simulation.js:56
    at Map.forEach (<anonymous>)
    at Object.tick (simulation.js:55)
    at layoutTick (force-graph.module.js:554)
    at Function.tickFrame (force-graph.module.js:540)
    at Function.comp.<computed> [as tickFrame] (kapsule.module.js:159)

my scenario is:
 I have two data source, first data source will return nodes with links. second data source will return free floating nodes with no link. this error happens when the second data source returns

**Comment by wunaidage** [comment]
looks like to be d3 error. I reported there too https://github.com/d3/d3-force/issues/182

**Comment by wunaidage** [comment]
looks like the package d3-force-3d overrides the simulation.js

in my local, simulation.js:56 is `force(alpha);` but this line of code is actually at line 48 of the latest code base:
https://github.com/d3/d3-force/blob/127cbb778ceba7d90848b6d2b7cf63e86a232e05/src/simulation.js#L48
so I found that simulation.js and manybody.js are recently changed by the commint:
https://github.com/d3/d3-force/commit/523a02d963f7caf28914b3557e28ce707cdd2d87#diff-6f8e3f3c294424d5ecab1e67514fec4167f39a50a475f6955e1ff28efdd3f54e

I checked my local d3-force node_module, I have version 2.1.1 and the simulation.js is the latest. but the d3-force-3d package is 2.1.0. 

@vasturiano you should upgrade d3-force-3d to 2.1.1 to fix this.

**Comment by wunaidage** [comment]
I temporarily fixed it by importing all d3 things from d3-force-3d

**Comment by vasturiano** [comment]
@wunaidage these conflicts should be fixed in the latest version (`1.35.0`). This version includes the update of `d3-force-3d` to full feature parity of `d3-force` `2.1.1`.

**Comment by wunaidage** [comment]
@vasturiano thanks!

**Comment by nevalla** [comment]
I faced the same error with version `1.36.2` (dependency of `react-force-graph` `1.37.5`) and `d3-force` `2.1.1`.

**Comment by nevalla** [comment]
I have a feeling that issue lies here:
https://github.com/vasturiano/d3-force-3d/blob/master/src/simulation.js#L109-L112

I have in the code like this:
```
fg.d3Force('charge', d3.forceManyBody().strength(-60).distanceMax(250));
```

I guess this force will be initialized by `nDim` as random function param, since `forceManyBody` in `d3-force` takes only two parameters.

**Comment by vasturiano** [comment]
@nevalla thanks for reaching out.

One way that you can solve this is by importing `forceManyBody` from the `d3-force-3d` module instead of `d3-force`.
This should make the force initialization signature match.
