### ISSUE TITLE
Data Structure for DAG?

### ISSUE THREAD

**Issue by Reldey** [vasturiano/force-graph#15]
Sorry if this is the wrong place for this, but I was wondering if there is an example data structure to use when the graph is set to a DAG layout, specifically 'td'. Not sure if the Force-Graph just detected and laid out the hierarchy based on link connections, or if the data set could be restructured to specify children.

**Comment by vasturiano** [comment]
@Reldey the data structure is the same as without the DAG mode, just a plain list of nodes and links.
The DAG hierarchy is extracted from the link connections in the data. The only requirement is that the data is acyclical. If a cycle is found in the structure, it will throw an error.

I've just added two examples to clarify the use of the DAG mode props:
https://vasturiano.github.io/force-graph/example/tree/
https://vasturiano.github.io/force-graph/example/dag-yarn/

**Comment by Reldey** [comment]
Amazing, thank you!

**Comment by Reldey** [comment]
Just another request, is there a way to make the links orthogonal in DAG mode? Was inspired here: https://beta.observablehq.com/@mbostock/tree-of-life
