### ISSUE TITLE
render process does not stop after host angular component destroy

### ISSUE THREAD

**Issue by wunaidage** [vasturiano/force-graph#153]
I found that the render process does not stop after the host component is destroyed. 
I started by noticing that the tab's CPU usage remains the same level after I go to another page which does not contain any force graph canvas. And our application get slower and slower after several visits of the force graph page. 
I put a console.log in nodeCanvasObject then found that the logging remains even after I have routed to another page and the canvas DOM has been removed. And when I revisit the canvas, there'll be another rendering process on top of the old one. This is a serious issue that will drag the performance down to the mud.
I try to assign graph to null when component destroy but it does not work.
is there's a way to completely destroy the Forcegraph?

**Comment by wunaidage** [comment]
I paused the animation when destroy and it looks like gonna fix the problem. but I'd rather to have the graph completely destroyed. please advise @vasturiano

**Comment by smartsl** [comment]
I just have exactly the same question.

**Comment by wunaidage** [comment]
I see https://github.com/vasturiano/force-graph/issues/148 seems to have the same question and pauseAnimation was mentioned.

**Comment by vasturiano** [comment]
@wunaidage there is a convenience `_destructor` shortcut method that you can invoke for this exact purpose:
https://github.com/vasturiano/force-graph/blob/6a9b1e7cd46e5686b4d98d060591174239fd3330/src/force-graph.js#L310-L313

You can invoke it via `myGraph._destructor()`. It simply pauses the rendering engine and empties the data structures.

**Comment by wunaidage** [comment]
Thank you! That's super cool!
