### ISSUE TITLE
Allow drawing custom shape to shadow canvas

### ISSUE THREAD

**Issue by petabyteboy** [vasturiano/force-graph#155]
**Is your feature request related to a problem? Please describe.**
I'm using nodeCanvasObject to draw a different shape to the main canvas. As you described in #11, the node's shape on the shadow canvas is still the default circle, so hover events behave very strangely.

**Describe the solution you'd like**
I would like to be able to define my own function to draw nodes to the shadow canvas via a `graph.nodeShadowCanvasObject((node, ctx, globalScale) => {...})`. I can use the __indexColor of each node to define my own hover area. 

**Describe alternatives you've considered**
I don't have any other ideas on how to accomplish this.

**Additional context**
https://github.com/vasturiano/force-graph/issues/11 was related

**Comment by petabyteboy** [comment]
I put in a hack on my fork's master branch: I moved nodeCanvasObject from the bindFG section to the bindBoth section so that the call gets passed through to both. Then I used the fourth argument to the function to determine which canvas I'm drawing on.
This works fine in my case but would break the API.

**Comment by vasturiano** [comment]
Thanks for this request @petabyteboy.

Took me a little time but finally got around to implement a solution for it.
There is a new method called `nodePointerAreaPaint(node, color, canvas)`. Any shape painted on that canvas (the shadow one) with the provided unique color will serve as a pointer trap for node interactions.

You can see it in action in [this example](https://vasturiano.github.io/force-graph/example/custom-node-shape/).
