### ISSUE TITLE
Modify CSS of hover tooltip

### ISSUE THREAD

**Issue by thatlittleboy** [vasturiano/force-graph#157]
Is there any way to modify the CSS of the tooltip box that appears upon hover? By default, when `nodeLabel` is set, a tooltip like 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/30731072/100498313-5bd0c580-319c-11eb-91c6-99b5e7f5300a.png">

appears. I know we can customize the text, but is there anyway to modify the way the tooltip box and its contents are displayed?
E.g. modify the max-width of the box, make the tooltip "sticky" if we mouse-over the tooltip box (something like [this](https://stackoverflow.com/a/52211120) so the user can highlight and copy the tooltip text), etc.

-----

Sample (simply modified from the Basics example):

```html
<head>
  <style> body { margin: 0; } </style>

  <script src="//unpkg.com/force-graph"></script>
  <!--<script src="../../dist/force-graph.js"></script>-->
</head>

<body>
  <div id="graph"></div>

  <script>
    // Random tree
    const N = 30;
    const gData = {
      nodes: [...Array(N).keys()].map(i => ({ id: i })),
      links: [...Array(N).keys()]
        .filter(id => id)
        .map(id => ({
          source: id,
          target: Math.round(Math.random() * (id-1))
        }))
    };

    const Graph = ForceGraph()
      (document.getElementById('graph'))
        .nodeLabel('id')
        .graphData(gData);
  </script>
</body>
```

Thanks.

**Comment by njifares** [comment]
There is a ccs class `graph-tooltip` attached to the tooltip div that you can use to customise the tooltip.

**Comment by thatlittleboy** [comment]
Yep, great. Thanks!
Just realized it's right there in the src code as well: https://github.com/vasturiano/force-graph/blob/master/src/force-graph.css#L8
