### ISSUE TITLE
Show a label within or around  a node

### ISSUE THREAD

**Issue by aoloo** [vasturiano/force-graph#165]
**Is your feature request related to a problem? Please describe.**
I wish there was a way to add labels within or around nodes.

**Describe the solution you'd like**
I would like the ability to show a label within a node or next to a node than a tooltip

**Describe alternatives you've considered**
The current `nodeLabel("[String]")` hows when a user hovers over a node. I have a use case where I need the label visible within the node or around. 

**Additional context**
![image](https://user-images.githubusercontent.com/66189547/104926685-79d1cf80-596e-11eb-95f3-38b13f6bc1a5.png)
![image](https://user-images.githubusercontent.com/66189547/104926710-80604700-596e-11eb-98e1-7fc880ef02ff.png)

**Comment by Alexithemia** [comment]
You will have to make it custom on the node object using .nodeCanvasObject([fn])

https://github.com/vasturiano/force-graph/blob/master/example/text-nodes/index.html

https://github.com/vasturiano/force-graph/blob/master/example/custom-node-shape/index.html

**Comment by aoloo** [comment]
@Alexithemia are there better examples in the documentation that can possibly get me closer to the desired result? I am new to d3  and if you have any example that can point me closer I would appreciate it a lot.

**Comment by aoloo** [comment]
```
 .nodeCanvasObjectMode(() => "after")
      .nodeCanvasObject((node, ctx, globalScale) => {
        const label = node.id;
        const fontSize = 12 / globalScale;
        ctx.font = ${fontSize}px Sans-Serif;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillStyle = "black"; //node.color;
        ctx.fillText(label, node.x, node.y + 20);
      })
```
      
      
![image](https://user-images.githubusercontent.com/66189547/104944764-afce7e00-5985-11eb-85fb-896f17d5eeb8.png)

After hours of research, I was able to achieve a close desired result by the configuration above. I think it would be benficial to the community adding an `api` in which we could set the label as either a tooltip or display label, and position it ourseleve.

**Comment by Mush-A** [comment]
Is there a way to use the above solution with custom node shapes and have different colors for the node and the text?

Right now the text and the node are the same colored therefore it's difficult to see the text when the node color is lighter.

![image](https://user-images.githubusercontent.com/73879146/203014204-d1954d2f-8970-45c3-8e16-7e91736a144a.png)

**Comment by vasturiano** [comment]
@Mush-A it's all customizable according to the way you implement your `nodeCanvasObject` method. Please check the built-in example:
https://github.com/vasturiano/force-graph/blob/2b7e6711880673f17f98cafb6267faad9f420637/example/text-nodes/index.html#L18-L34
