### ISSUE TITLE
Is there any possibility to set `nodeVal` as a rectangle instead of a circle?

### ISSUE THREAD

**Issue by ivanbenavidesvt** [vasturiano/force-graph#167]
**Is your feature request related to a problem? Please describe.**
I have some nodes which are rectangles but the active area of them is a circle. When the user tries to hover or drag them, there are some parts that are not actionable.

**Describe the solution you'd like**
I would like to have a `nodeVal` function that allows to create a rectangle actionable area of the node

nodeVal(width, height)

**Additional context**
<img width="474" alt="Screenshot 2021-01-26 at 08 59 03" src="https://user-images.githubusercontent.com/47318873/105816913-32be8c80-5fb5-11eb-85c1-5aa41fe99847.png">

Red circle is the only actionable area of the rectangle node.

**Comment by sr1k3sh** [comment]
nodeCanvasObject this will let you create custom object. i applied stroke and canvas text from there

**Comment by ivanbenavidesvt** [comment]
nodeCanvasObject lets you create the visible shape, but not the actionable shape.
- Visible shape: Rectangle
- Actionable shape: Red circle.

For instance: when a user clicks on the rectangle nothing happens. The user must click in the red circle to trigger the "on click" event

**Comment by vasturiano** [comment]
@ivanbenavidesvt the method `nodePointerAreaPaint` lets you define a custom area for pointer interactions.

See how it's being used in [this example](https://github.com/vasturiano/force-graph/blob/master/example/custom-node-shape/index.html).

**Comment by ivanbenavidesvt** [comment]
Thanks! That's what I needed. :)
