### ISSUE TITLE
CPU usage still high even with paused animations or disabled event listeners

### ISSUE THREAD

**Issue by bashovski** [vasturiano/force-graph#169]
**Describe the bug**

Hello, again. So basically, we are experiencing high CPU usage even with a low amount of nodes/edges in the graph.
The graph is unloaded by clearing the graph data: 
```js
        this.graphInstance.pauseAnimation();
        this.graphInstance.graphData({
          nodes : [],
          links : []
        });
```

I've tried resuming the animation and populating the data once a graph should be reloaded, but the result is the same.
We are also requiring the graph to emit those events:
```
onBackgroundClick
onNodeClick
onLinkClick
```

We have also applied custom link curvature and we also apply custom canvas objects where needed (only 5-10 have a canvas object which is a basic non-solid text).

**Expected behavior**
Basically, the graph shouldn't cause high CPU usage since it shouldn't be doing anything unless user interacts with it.

**Screenshots**
An example of how the graph implementation looks like: 
```force-graph loading 113 nodes 809 links```
![image](https://user-images.githubusercontent.com/48890281/107070459-ae091500-67e3-11eb-845a-805ab3af5b3e.png)

Here's the performance monitor (avg. CPU usage without having the graph opened is between 2.5 and 5%): 
![image](https://user-images.githubusercontent.com/48890281/107070600-da249600-67e3-11eb-857f-d1a27cdfa743.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version Version 88.0.4324.150 (Official Build) (x86_64)

(also happens on other browsers)

**Additional context**
I've also posted another issue last year which could be related to this one: [issue](https://github.com/vasturiano/force-graph/issues/148)

Looking forward to hearing from you!

**Comment by vasturiano** [comment]
@bashovski thanks for your report. 

I've added some performance improvements to the rendering cycle that automatically pauses redraws when the force simulation engine is halted. This should bring the cpu usage of the module to a minimum after the cooldown phase.
The default cooldown phase lasts for `15s`, if that is too long for your case you can reduce this period via either `cooldownTime` or `cooldownTicks`.

Keep in mind the redrawing is only paused if there's no need to visual changes needed in the canvas. For cases which the canvas needs updating, for instance when there are directional particle animations, the redrawing remains active.

It's also possible to bypass this automation altogether, for some custom cases which require continuous redrawing of the canvas, like so:
```js
myGraph.autoPauseRedraw(false)
```

Let me know if you observe an improvement with this new functionality.
