### ISSUE TITLE
unpkg link is not available

### ISSUE THREAD

**Issue by EylonSho** [vasturiano/force-graph#17]
Hi,

The dependency seems to be no longer available via:
`<script src="//unpkg.com/force-graph"></script>`

**Comment by vasturiano** [comment]
@EylonSho this is related to an issue going on in the cdn (unpkg): 
https://github.com/unpkg/unpkg.com/issues/156

If you need to fix it immediately, you can just reference the bundle file explicitly in your script tag:
```
https://unpkg.com/force-graph/dist/force-graph.min.js
```

**Comment by EylonSho** [comment]
Thank you very much!
