### ISSUE TITLE
Link text overlaps with curvature

### ISSUE THREAD

**Issue by aoloo** [vasturiano/force-graph#170]
Implementing Link curvature with text causes link text to overlap. 
![image](https://user-images.githubusercontent.com/66189547/110053589-b5aad380-7d27-11eb-9f35-31a7deb985fa.png)

Any example or guidance implementing two nodes with link curvature associated with text would be greatly appreciated. 
Modifying `textPos` seems to not do the trick.

   
     const textPos = Object.assign(
            {},
            ...["x", "y"].map((c) => ({
              [c]: start[c] + (end[c] - start[c]) / 2, // calc middle point
            }))
          );

This is what I am trying to achieve 
![image](https://user-images.githubusercontent.com/66189547/110054282-d58ec700-7d28-11eb-8cc6-a2462479bf8d.png)

**Comment by vasturiano** [comment]
@aoloo I'm guessing you're referring to this example: https://github.com/vasturiano/force-graph/blob/master/example/text-links/index.html

You're on the right track though. `textPos` is basically the coordinates of the text center based on the link data. In that example it's set to be the exact midpoint between the two nodes. If you'd like a different position you just have to replace that logic with where you'd like the label to be position, relative to the nodes' coordinates.

**Comment by aoloo** [comment]
Thank you!
