### ISSUE TITLE
How to set a distance between 2 nodes?

### ISSUE THREAD

**Issue by meghasahane** [vasturiano/force-graph#172]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vasturiano** [comment]
@meghasahane you can set the link force's [distance attribute](https://github.com/d3/d3-force#link_distance). Like so:
```js
myGraph.d3Force('link').distance(link => /* your logic */)
```

**Comment by meghasahane** [comment]
Thanks @vasturiano
