### ISSUE TITLE
Can we connect 1st and last node with together to create a triangle or square shape?

### ISSUE THREAD

**Issue by meghasahane** [vasturiano/force-graph#173]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vasturiano** [comment]
Yes, that's easily doable. F.e.: https://vasturiano.github.io/force-graph/example/curved-links/

**Comment by meghasahane** [comment]
Thanks @vasturiano
