### ISSUE TITLE
Disable node fixing

### ISSUE THREAD

**Issue by germankatz** [vasturiano/force-graph#181]
Disable node fixing
First of all thanks for this amazing thing that simplifies a lot!

---
**name**: Disable node fixing
**about**: The idea is to return to default state after using `onNodeDragEnd`, for example I have a checkbox that works for fixing the positions, It would be great the possibility of unchecking the box for free node movement again.

---
The only solution I have come across is reload the whole thing but I would be loosing the positions, and saving them means a lot of work involved

**Comment by vasturiano** [comment]
@germankatz you can just iterate through your nodes and remove the fixing attributes.
Something like:
```js
graphData.nodes.forEach(node => {
  delete node.fx;
  delete node.fy;
})
```

**Comment by germankatz** [comment]
Thanks! It's also make me realize that I can fix all the nodes when checking the box with:
```
gData.nodes.forEach(node => {
    node.fx = node.x;
    node.fy = node.y;
})
```
