### ISSUE TITLE
How to have linkOpacity for 2D graph 

### ISSUE THREAD

**Issue by Chinmay-k96** [vasturiano/force-graph#187]
As of now linkOpacity is only available for 3D, How can i do it for 2D please share info in this

**Comment by vasturiano** [comment]
@Chinmay-k96 you can set the alpha channel on the `linkColor`, as in this example:
https://github.com/vasturiano/force-graph/blob/3e0c1d468cb7c6c82b6c0829a6cd1d8814709b1f/example/large-graph/index.html#L36

**Comment by Chinmay-k96** [comment]
thank you so much
