### ISSUE TITLE
Get graph node object by JSON data

### ISSUE THREAD

**Issue by chinjen** [vasturiano/force-graph#193]
Hi,

I'm trying to make interaction between two graph.

![sample](https://user-images.githubusercontent.com/39974700/118268831-7ac7d780-b4f0-11eb-8a3e-ae5eb96c3574.png)

A graph and B graph both have same node A which means node has same data. I would like click B graph node A then A graph will centerAt node A simultaneously.

Now we can use current function get data by interact with node, but in source code can we get node object by data ? So that I can centerAt A graph by node's coordinate.

Below is my code.

`                       

                        let B_rep_graph;
                        let A_rep_graph;

                        fetch('/bet_fake_network_rep_ver').then(res => res.json()).then(data => {
                        const elem = document.getElementById('fake_net');

                        B_rep_graph= ForceGraph()(elem)
                            .backgroundColor('#FBFCFD')
                            .nodeRelSize(6)
                            .nodeColor('group')
                            .linkDirectionalArrowLength(6)
                            .nodeLabel(node => `${node.user}: ${node.description}`)
                            .linkColor(() => 'rgba(0,0,0,0.2)')
                            .onNodeHover(node => elem.style.cursor = node ? 'pointer' : null)
                            .onNodeClick( node => {

                                //window.alert(node.id);
                                //window.alert(typeof(true_rep_graph));
                                //window.alert(node.x);
                                //window.alert(node.y);
                                //window.alert(typeof(node));
                                //console.log(true_rep_graph.graphData().nodes);
                                //let true_nodes = true_rep_graph.graphData().nodes;
                                //window.alert(typeof(true_nodes));

                                let find_node_id;
                                for (const [key, value] of Object.entries(true_nodes)){
                                    if (node.id == value.id) {
                                        find_node_id = value.id;
                                    }
                                }

                                window.alert(find_node_id);
                                
                            })
                            .graphData(data)
                            .width(550)
                            .height(550);
                        });

                        fetch('/bet_true_network_rep_ver').then(res => res.json()).then(data => {
                        const elem = document.getElementById('true_net');

                        A_rep_graph= ForceGraph()(elem)
                            .backgroundColor('#FBFCFD')
                            .nodeRelSize(6)
                            .nodeColor('group')
                            .linkDirectionalArrowLength(6)
                            .nodeLabel(node => `${node.user}: ${node.description}`)
                            .linkColor(() => 'rgba(0,0,0,0.2)')
                            .onNodeHover(node => elem.style.cursor = node ? 'pointer' : null)
                            .onNodeClick( node => {
                                window.alert(typeof(fake_rep_graph));
                            })
                            .graphData(data)
                            .width(550)
                            .height(550);
                        });`

**Comment by vasturiano** [comment]
@chinjen once you find the equivalent node data object from the other graph data structure, you can access its current coordinates via `node.x` and `node.y`.

This example shows how to use those attributes to center on:
https://github.com/vasturiano/force-graph/blob/c5f604ec71db26be100e203bb4beeb57ada3f820/example/click-to-focus/index.html#L24-L25

**Comment by chinjen** [comment]
Thanks for sharing example, but I would like to NodeClick on graph B but zoom in graph B. Is it possible to click graph B then know the same node on graph A coordinates ?

**Comment by chinjen** [comment]
I mean could I get node A coordinate on graph A by click same node on graph B ?

**Comment by vasturiano** [comment]
Assuming you have two separate data structures, one for each graph, you just need to do the lookup on one from the other, possibly by node id. But it looks like you're doing that already to some extent here:
```js
let find_node_id;
for (const [key, value] of Object.entries(true_nodes)){
    if (node.id == value.id) {
        find_node_id = value.id;
    }
}
```

**Comment by chinjen** [comment]
node.id is the data that I click node from graph B then I found the find_node_id from graph A. But I cannot get the graph A node A coordinate by value.id. Is it possible reverse lookup node's coordinate by its data ?

**Comment by vasturiano** [comment]
@chinjen as mentioned in my first message, the coordinates are attached to node's data, in the `x` and `y` attributes.

**Comment by chinjen** [comment]
@vasturiano I see. thank you so much. such that the graph a data attribute I have already find in true_nodes.
