### ISSUE TITLE
Canvas-drag causes onBackgroundClick callback

### ISSUE THREAD

**Issue by smartsl** [vasturiano/force-graph#196]
**Describe the bug**
After canvas dragging, when mouse button is up, the onBackgroundClick callback is invoked.

**To Reproduce**
1. Drag the canvas
2. Release the mouse button
3. onBackgroundClick callback is called.

**Expected behavior**
onBackgroundClick callback should not be called. Or there is a way to tell the difference from a normal click.

**Screenshots**
Not required.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 90.0.4430.212

**Additional context**
This occurs in force-graph v1.40.5
This doesn't occur in force-graph v1.32.3
Other force-graph versions are not tested.

**Comment by smartsl** [comment]
I've digged into source codes. It seems that the variable 'isPointerDragging' takes action here. The difference between two versions are where it's been set:
1) In the old version, it's been set in 'pointermove' & 'pointerdown' event listeners.
2) In the new version, it's been set in "d3Drag().on('drag/end')" event listeners.

Too subtle for me to understand and find out a patch. Could anyone help to fix this. Thanks :-).

I guess this line:
```js
state.isPointerDragging = false;
```
in d3Drag().on('end') may be unnecessary?

**Comment by vasturiano** [comment]
Thanks for the report @smartsl. This should now be fixed in the latest version (`1.40.6`).
