### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by fabiospampinato** [vasturiano/force-graph#198]
**Describe the bug**

This library has a massive performance issue: even if nodes are not moving by any perceivable amount after a tick (there should probably be a setting for this), even if the simulation has cooled down, even if the mouse is not hovering any item in the graph and the canvas is not being panned or zoomed this library is still re-rendering everything at each tick, which just wastes a lot of resources (for large graphs especially) for doing nothing of value.

**Expected behavior**

There should be a way to stop re-paints when they are useless.

**To Reproduce**

Have a graph open.

**Comment by fabiospampinato** [comment]
I've just now realized that there are "pauseAnimation" and "resumeAnimation" methods, but I think using those disable all the mouse interactions too, which isn't what I need.

**Comment by vasturiano** [comment]
@fabiospampinato thanks for reaching out. 

As specified by the `autoPauseRedraw` setting, if that is enabled (`true` by default) the re-rendering will be halted whenever the graph finishes cooling down.
You should remember that by default the cooldown period is 15s, but that can be modified via `cooldownTicks` or `cooldownTime`.

Are you observing a different behaviour?

**Comment by fabiospampinato** [comment]
@vasturiano Wait, sorry, I hand't noticed that I'm a few releases behind and "autoPauseRedraw" isn't available in the version I'm using.

If that pauses rendering strategically while still allowing for interactivity then I guess that fixes it. 

If it doesn't allow for interactivity then it should probably be tweaked to allow for it, for what I need I duct-taped [this commit](https://github.com/fabiospampinato/force-graph/commit/70e1254cd8e3738d0f5480b1815a4faa7d07ffce) together that fixes the issue for me, it seems to me that if `force-graph` doesn't already work like this it should be able to if it only knew how long the longest animation (on hover for example) took, and that could just be another configurable parameter.

**Comment by vasturiano** [comment]
@fabiospampinato that functionality does take into account interactivity. It re-wakes the rendering whenever graph interaction or force re-heating is detected.

**Comment by fabiospampinato** [comment]
Nice, closing this then.
