### ISSUE TITLE
[Question] Is there any way to debug nodePointerAreaPaint?

### ISSUE THREAD

**Issue by thisisthepathfinder** [vasturiano/force-graph#204]
Hi there,

I've been trying to use force-graph with Vue and seem to be experiencing an issue where the pointer areas are are offset-ed from the actual node. I reproduce my code without Vue and it worked fine on both Chrome / Firefox. 😅 So, I was wondering if there's any hints you could give on debugging nodePointerAreaPaint? Even as simple as being able to visually show it would help a lot.

**Issue Footage**
https://streamable.com/4af453

**Rough Repro Without Vue**
https://codepen.io/thisisthepathfinder/pen/mdWGWqy

Thanks!

**Comment by vasturiano** [comment]
@thisisthepathfinder thanks for reaching out.

One thing you can do is add an extra shape (potentially filled with a semi-transparent color so you can see through) to your `nodeCanvasObject` with the same code as you have in `nodePointerAreaPaint`. The placement of both functions should be equivalent, so you can use that to visually debug it.

**Comment by thisisthepathfinder** [comment]
Ah yes, thank you! I will do that, should be able to figure out from there.

Thank you once more for the hard work!
