### ISSUE TITLE
How to get Node's position (x,y) without click on Node

### ISSUE THREAD

**Issue by hukacode** [vasturiano/force-graph#205]
Hello,

I used this snippet and searched all document but cannot find how to get Node's position.

```js
let true_nodes = graph.graphData().nodes;
for (const [key, value] of Object.entries(true_nodes)) {
      if (value.id == nodeId) {
        // graph.d3Force('center', null);
        // graph.centerAt(value.x, value.y, 1000);
        // graph.zoom(4, 1000);
        break;
      }
}
```

The use case is I have a graph and a dynamic node id. I want to focus on that node every time load graph (without click on that Node).

Could you please show a snippet or the document where I can search for it?
Thank you for your time and effort.

**Comment by vasturiano** [comment]
@hukacode you node objects should have `x`, `y` coordinates attributes, but only after the engine is initialized. Is it possible that you're running through that code before the graph is rendered? That would explain why the attributes are not present.

**Comment by hukacode** [comment]
Hi @vasturiano ,

Thank you so much for your response and hint.
It is exactly what you described.

I put my code into `.onEngineStop` then it worked.

```js
graph.onEngineStop(() => {
  let true_nodes = graph.graphData().nodes;
  for (const [key, value] of Object.entries(true_nodes)) {
    if (value.id == nodeId) {
      graph.centerAt(value.x, value.y, 500);
      graph.zoom(4, 500);
      break;
    }
  }
});
```
