### ISSUE TITLE
conditional animation for link

### ISSUE THREAD

**Issue by tarun080698** [vasturiano/force-graph#206]
Can I use conditional animation for link **dashed** and **particles**, both in a single graph based on a link condition or flag?

**Comment by tarun080698** [comment]
@vasturiano, how will I specify here which link should be seen as a dashed link or particle link using this prop?

what is want is something like [this](https://vasturiano.github.io/force-graph/example/dash-odd-links/) but here just like dashed links have an animation of moving dashed, I want the other link also have the animation of moving particles. I want both in a single graph.

**Comment by vasturiano** [comment]
They are independent features, you can setup any link to have just one, both are none. For instance, if each of your links has a flag `useDashes` that states whether it should use dashes or particles, you can do:
```js
myGraph
  .linkDirectionalParticles(link => link.useDashes ? 0 : 2)
  .linkLineDash(link => link.useDashes && [5, 5])
```

**Comment by tarun080698** [comment]
@vasturiano, so you are saying that I can use any one of the link styles at a time? I cant show both link styles **moving-particles** and **moving-dashes** ? and by moving I mean I want to add animation in both. 
I am trying to show some links as **moving dashes** and some as **moving particles**. 

In the below gif, you can see that I have added both types of link styles and when I enter into canvas, it starts to behave like this 
![CPT2106160924-1303x801](https://user-images.githubusercontent.com/53266806/122155596-e94bdc80-ce84-11eb-9047-fd6c79796a9b.gif)
When I hover, the animation stops and nodes start to move/contract.
Here is my code: 

`linkColor={() => '#757575'}
linkDirectionalParticles={link => (link.dashed ? 0 : 4)}
linkDirectionalParticleColor={() => 'lightgrey'}
linkDirectionalParticleWidth={link => link.dashed ? 0 : 2}
linkDirectionalParticleSpeed={link => link.dashed ? 0 : 10 * 0.001}
linkLineDash={link => link.dashed && [5, 5]}`

**Comment by vasturiano** [comment]
@tarun080698 yes, that should be possible.

As for your hover glitches, it's a guess but it looks like you may be unnecessarily re-rendering the graph when your pointer moves over the canvas. If that's the case, probably memoizing the accessor methods (with `useCallback`) may solve the issue.
This is more of a React thing however, so unrelated to this module.

**Comment by tarun080698** [comment]
@vasturiano can give me a small example of how to set **useCallback** in my use case?  here's my code
 ```
<ForceGraph2D
            ref={fgRef}
            graphData={props.signalData}
            backgroundColor={'#18191d'}
            height={props.heightEle}
            width={props.widthEle}
            nodeId="id"
            autoPauseRedraw={false}
            nodeCanvasObject={(node, ctx) => {...}
            maxZoom={10}
            onEngineStop={() => {
              if (!stopEngine) {
                fgRef.current.zoomToFit(500, 100)
                setStopEngine(true)
              }
            }}
            cooldownTicks={100}
            linkColor={['#757575']}
            linkDirectionalParticles={link => (link.current_case ? 4 : 0)}
            linkDirectionalParticleColor={['lightgrey']}
            linkDirectionalParticleWidth={[3]}
linkDirectionalParticleSpeed={() => 1 * 0.01}
          />
```

**Comment by vasturiano** [comment]
@tarun080698 that falls too outside the scope of this module. But you can look in some examples on `react-force-graph` (for example [here](https://github.com/vasturiano/react-force-graph/blob/e67177b3522e2ffd212f807cbb6b74ed04a39ab6/example/click-to-focus/index.html#L22)), or turn to a React oriented forum for help.

**Comment by tarun080698** [comment]
@vasturiano after adding this 
`linkDirectionalParticles={4}
linkDirectionalParticleColor={() => 'lightgrey'}
linkDirectionalParticleWidth={link => link.current_case === 3 ? 3 : 0}
linkDirectionalParticleSpeed={() => 1 * 0.01}`
It is not rendering my link particles though my condition is true. And if I remove this line then it takes **linkDirectionalParticleWidth** as **3** and renders particles.

> They are independent features, you can set up any link to have just one, both are none. For instance, if each of your links has a flag `useDashes` that states whether it should use dashes or particles, you can do:
> 
> ```js
> myGraph
>   .linkDirectionalParticles(link => link.useDashes ? 0 : 2)
>   .linkLineDash(link => link.useDashes && [5, 5])
> ```

tried this also for the number of particles but still not working.

**Comment by vasturiano** [comment]
@tarun080698 it's difficult to say without more context. Could you make a simple example on codesandbox, if you're still having an issue?

**Comment by tarun080698** [comment]
@vasturiano there's was logic issue while i was setting flag for links and that was causing the issue. It is regretful that I had to ping you again and again. Thanks for help though. Have a nice day and sorry for the trouble.
