### ISSUE TITLE
Dynamic width of canvas

### ISSUE THREAD

**Issue by thatlittleboy** [vasturiano/force-graph#207]
Is there a way to dynamically modify the width of the canvas in which the force graph is rendered?

Here is a modified example (background coloured black so we can see the canvas size):
```
<head>
  <style> body { margin: 0; } </style>

  <script src="//unpkg.com/force-graph"></script>
  <!--<script src="../../dist/force-graph.js"></script>-->
</head>

<body>
  <div id="graph"></div>

  <script>
    // Random tree
    const N = 30;
    const gData = {
      nodes: [...Array(N).keys()].map(i => ({ id: i })),
      links: [...Array(N).keys()]
        .filter(id => id)
        .map(id => ({
          source: id,
          target: Math.round(Math.random() * (id-1))
        }))
    };

    container = document.getElementById('graph');
    const Graph = ForceGraph()
      (container)
        .nodeLabel('id')
        .backgroundColor("#101020")
        .width(container.clientWidth).height(600)
        .graphData(gData);
  </script>
</body>
```

For example, here, I can use `container.clientWidth` in the initial rendering of the graph to dynamically fix the width to 100%.
But if I then resize the window, the canvas remains at that width.

Is there a way to achieve dynamic resizing of the canvas depending on user interaction with the browser window?

Btw: I don't mind if after canvas resizing, the graph is not centered, or "cut off" because the canvas became smaller. As long as the graph elements (nodes, links) themselves are not affected, e.g. stretched/squished.
(Because a naive way to achieve this is simply to reassign the width of canvas after the drawing is done, but that will distort the entire canvas' contents rather than adjusting the canvas size itself).

**Comment by 6r1d** [comment]
I think I'm missing something here, but did you find some API features to allow dynamic resizing?

**Comment by vasturiano** [comment]
@6r1d thanks for reaching out.

This functionality is beyond the scope of this library, but you can easily use a 3rd party module to monitor window resize events and inject `width` and/or `height` properties into `force-graph`.

For example, if you would use [element-resize-detector](https://github.com/wnr/element-resize-detector) to pick one, you would just need to do something like:
```js
const Graph = ForceGraph()
  (document.getElementById('graph'));

elementResizeDetectorMaker().listenTo(
  document.getElementById('graph'),
  el => Graph.width(el.offsetWidth)
);
```

[Here is an example](https://vasturiano.github.io/force-graph/example/responsive/) of this setup, and you can find the [example code here](https://github.com/vasturiano/force-graph/blob/master/example/responsive/index.html).

**Comment by 6r1d** [comment]
@vasturiano, thank you both for a great library and a recipe!
It works for me [here](https://6r1d.github.io/CLIP_graph_visualized/index.html).
(Changed it to track height, as well.)

**Comment by Perdyx** [comment]
> @vasturiano, thank you for both a great library and a recipe!
> It works for me [here](https://6r1d.github.io/CLIP_graph_visualized/index.html). (Changed it to track height, as well.)

I know this is a little late, but I figured I would ask anyway in the off chance you have any pointers. I'm trying to do something similar, but it's not working for me. I tried using your code for the resize and graph styles (see below), but I have an issue where the graph canvas only gets bigger vertically and won't resize to be smaller. The width works fine, though. Did you ever have this issue?

Here is the code I used (from your project):
```css
html,
body,
#graph {
    height: 100%;
    width: 100%;
    margin: 0;
    overflow: hidden;
}
```

```js
elementResizeDetectorMaker().listenTo(
    document.getElementById('graph'),
    function(element) {
        Graph.width(element.offsetWidth)
        Graph.height(element.offsetHeight)
    }
)
```

**Comment by bglasgo** [comment]
I used the built in ResizeObserver function of JavaScript and it seems to work pretty well without adding an additional library.

`const resize = new ResizeObserver(function (entries) { 
  let rect = entries[0].contentRect
  Graph.width(rect.width).height(rect.height)
})
resize.observe(document.querySelector("#MapContainer"));`
