### ISSUE TITLE
improve performance by only redrawing nodes visible on screen

### ISSUE THREAD

**Issue by xlfe** [vasturiano/force-graph#209]
**Is your feature request related to a problem? Please describe.**

I'd like to improve rendering performance by only redrawing those nodes visisble on the canvas

**Describe the solution you'd like**

An option to disable the drawing of a node if it is not on the canvas (ie off screen)

**Describe alternatives you've considered**

I looked at implementing this myself using the nodeVisibility function, but getGraphBbox doesn't help as it is the bounding box of the nodes, not the "viewport".

**Comment by vasturiano** [comment]
@xlfe thanks for reaching out.

Using `onZoom(({ k, x, y }) => ...)` you should be able to keep state of the viewport boundary coordinates, by cross-referencing that with the canvas width/height. Then you can convert those coordinates to the graph domain using `screen2GraphCoords(x, y)` to determine the bounding box of nodes/links in view.

**Comment by xlfe** [comment]
ok -  thank you -  will give that a go
