### ISSUE TITLE
Force pointerAreaPaint

### ISSUE THREAD

**Issue by xlfe** [vasturiano/force-graph#219]
**Is your feature request related to a problem? Please describe.**

I have an effect that changes the look of the nodes on hover, to allow the user to click on various things. As part of that, I set a value on the node which the nodepointerAreaPaint checks to see how big the pointer area needs to be...

At the moment, if the user hovers over the node and tries to click on one of the new elements (outside the original pointer area) the click goes through to the background because the pointerArea has not been redrawn (I think the default is 800ms).

**Describe the solution you'd like**
Some way to trigger a pointerAreaRedraw when I know the sizes have changed?

**Comment by vasturiano** [comment]
@xlfe thanks for reporting this issue.

I pushed a fix for it, where the redraw of the pointer area is flushed whenever either `nodePointerAreaPaint` or `linkPointerAreaPaint` is invoked externally.

Could you please try with the latest version (`1.42.2`) to see if it fixes the issue?

**Comment by xlfe** [comment]
Thanks @vasturiano - sorry I'm confused, how do I call nodePointerAreaPaint for a single node (the one that has been hovered) ?

**Comment by vasturiano** [comment]
@xlfe you don't. You call that method for all the nodes, but inside that callback you can define some logic that singles out nodes and paints them differently, for example if they're being hovered.

**Comment by xlfe** [comment]
ok thanks for the clarification
