### ISSUE TITLE
yarn.lock Dependency Graph Example Sometimes Doesn't Render

### ISSUE THREAD

**Issue by manunamz** [vasturiano/force-graph#220]
**Describe the bug**
When clicking on the `yarn.lock dependency graph (DAG mode)` example in the project README, the graph does not always render and presents a blank screen (with controls).

(After re-freshing a few times, the graph started working on its own)

**To Reproduce**
See above.

**Expected behavior**
To see another great vasturiano-made graph example.

**Screenshots**
![yarn lock dependency graph](https://user-images.githubusercontent.com/75578970/129751366-65e08d61-ca4c-4bfc-af6d-6d7112304f08.png)

**Desktop (please complete the following information):**
 - OS: macos (M1)
 - Browser: Experienced behavior on chrome, firefox, and brave.
 - Version: Whatever is on the current README.

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**🎉**
Thanks for the amazing project. ☺️

**Comment by vasturiano** [comment]
Thanks for the report @manunamz. There was an intermittent issue with importing one of the necessary packages in that example via bundle.run. Basically this url was intermittently failing: https://bundle.run/@yarnpkg/lockfile.
Pinning down the lib version fixed it, so you shouldn't see the problem anymore. 👍 

https://vasturiano.github.io/force-graph/example/dag-yarn/
