### ISSUE TITLE
Is `targetNode` in Tree Example Used?

### ISSUE THREAD

**Issue by manunamz** [vasturiano/force-graph#221]
**Describe the bug**
More of a question than a bug: Is **`targetNode` not being used from the [tree example](https://github.com/vasturiano/force-graph/blob/master/example/tree/index.html#L63)**? The only other place in the codebase I could find `targetNode` was [here](https://github.com/vasturiano/force-graph/blob/3e0c1d468cb7c6c82b6c0829a6cd1d8814709b1f/src/dagDepths.js#L15), but it is not read from the set of parameters fed into the`link` data.

(It would be really neat if the `targetNode` usage in the example was a typo, because if I'm reading this right, that would allow for the same set of graph data to be processed by both the vanilla force graph and the dag force graph...Which would be great)

Again, fantastic projects. 🎉

**Comment by vasturiano** [comment]
@manunamz yes that `targetNode` attribute in each link object is not needed. It's merely there for convenience but it can be safely removed and the example would still work. Essentially the `force-graph` module does not look or require that attribute to be present.
