### ISSUE TITLE
Toggle link visibility

### ISSUE THREAD

**Issue by pournaki** [vasturiano/force-graph#223]
Is it possible to _toggle_ a graph's link visibility? 

I did not figure out how to do that. When I create a button that calls `Graph.linkVisibility('false')`, it effectively hides the links. However, if I want to show them again calling `Graph.linkVisibility('true')`, nothing happens. 

Thank you very much!

**Comment by vasturiano** [comment]
@pournaki if you want to toggle the visibility of all the links you should pass a `boolean` value not a `string`, like so: `linkVisibility(true)`.

**Comment by pournaki** [comment]
@vasturiano thank you for the swift answer, rookie mistake...
