### ISSUE TITLE
how to know the mouse position when mouse hovering custom thing

### ISSUE THREAD

**Issue by Mccreew** [vasturiano/force-graph#23]
I want to implement this effect that when click a node it shows more tool like in neo4j browser.
![Selection_048](https://user-images.githubusercontent.com/30411866/54863921-c0ae0880-4d89-11e9-9ffb-6f83055f8f31.png)

here is my implement:

![image](https://user-images.githubusercontent.com/30411866/54863943-1b476480-4d8a-11e9-97bc-795d39ca6b15.png)

next, I want to capture the mouse position to know whether it is hover the three tools, and which one. but mouse position in the canvas "mousePos.x" and "mousePos.Y" is not same as the node position.

I want to know how to connect the relationship between mousePos and node's position. so when click a node, it show three tools, and then i can know which tool mouse hovering

**Comment by vasturiano** [comment]
@Mccreew you can determine the current transform of the canvas by calling `.centerAt()` (x, y translation) and `.zoom()` (scale). Using those you can calculate where the mouse pointer is in relation to the node. 
Hopefully that helps.

**Comment by Mccreew** [comment]
thanks for your comment, finally i use "canvas-color-tracker" solve this problem, and it is simple.
