### ISSUE TITLE
Variable link strength based on link.value?

### ISSUE THREAD

**Issue by caiannello** [vasturiano/force-graph#239]
Hi.  I'm doing code flow graphs using force-graph and it is brilliant! 

However, when graphing more complex examples, it can get quite tangled. One solution I want to investigate is to make some links much less 'springy' than the others- on the basis of link.value. 

My latest attempt causes an exception that I don't recognize: 
```
Uncaught TypeError: e.id is not a function
    at Function.update (force-graph:5)
    at force-graph:2
    at u (force-graph:2)
```
Am I even close?  Thanks!

```
    //  want lower link springiness for calls, tailcalls, and returns
    function linkStrength(link) 
    {
      var stnval = 1 / Math.min(count(link.source), count(link.target));
      if (link.value < 4)
        stnval/=8;
      return stnval;
    }

      const Graph = ForceGraph()
      (document.getElementById('graph'))
        .graphData(data)
        .nodeId('id')
        .nodeVal('val')
        .nodeLabel('id')
        .nodeAutoColorBy('group')
        .linkAutoColorBy('value')       
        .linkSource('source')
        .linkTarget('target')
        .linkDirectionalArrowLength(6)
        .linkWidth(2)
        .d3Force("link",  linkStrength);
```

**Comment by vasturiano** [comment]
Hi @caiannello, thanks for reaching out.

If I understand correctly you are trying to set the [strength method of the forceLink force](https://github.com/d3/d3-force#link_strength).

That would be achieved with this syntax instead:

```js
Graph.d3Force('link').strength(linkStrength)
```

**Comment by caiannello** [comment]
Thank you for your help.  

That worked, and it greatly improved the graph. 

```
    //  lower spring constant for calls, tailcalls, and returns
    function linkStrength(link) 
    {
      var stnval = 1.0;
      if (link.value < 4)
        stnval/=100.0;
      return stnval;
    }
```

![Untitled](https://user-images.githubusercontent.com/10247237/144343143-d06c2bff-7033-4570-8bfe-5ba00f442a55.png)
