### ISSUE TITLE
Disable dagMode with null or 'null'?

### ISSUE THREAD

**Issue by andresmrm** [vasturiano/force-graph#24]
Hi! And thanks for this amazing lib!

I'm starting my graph with `.dagMode('lr')` and then trying to disable it with `.dagMode(null)` without success. That is the `null` value in the example:
https://github.com/vasturiano/force-graph/blob/master/example/tree/index.html#L20

After sometime I've found out it do disable with `.dagMode('null')` or any other non-valid dag mode string (like `.dagMode('aaaaa')`.

I guess the example is working because the way it is because the gui select convert `null` to `'null'` automatically. But if the right is `'null'`, maybe it would be better to fix the example.

**Comment by vasturiano** [comment]
Ola Andre!

Thanks for the report. There was a small bug that was not un-fixing the nodes positions when switching from a `dagMode` into a disabled (`falsy` value) state.
This is now fixed. You should be able to get the desired behavior by doing `.dagMode(null)` or `.dagMode(false)`, if you use the latest version of the library (`1.14.5`).

**Comment by andresmrm** [comment]
Thanks! =D
