### ISSUE TITLE
Saving Graphs

### ISSUE THREAD

**Issue by ingodahn** [vasturiano/force-graph#245]
When an automatically created graph has been manually beautified by dragging nodes it would be desirable to save it to a local file such that it can be later reloaded.
Trying `JSON.stringify(Graph.graphData())` leads to a `too much recursion` error.

**Comment by vasturiano** [comment]
@ingodahn you should extract only the properties of the data that you are interested on, such as the nodes' `x` and `y` attributes.

**Comment by ingodahn** [comment]
Thanks, that's working well.
