### ISSUE TITLE
Link arrows are not reaching some nodes due to node size difference

### ISSUE THREAD

**Issue by angetong** [vasturiano/force-graph#246]
**Describe the bug**
In our graph, we’re using `nodeVal` so that some nodes appear large (size 4) and others appear small (size 1). We are also setting `lineDirectionalArrowRelPos` to 1, which should position the arrowhead at the end of the line touching the target node. But instead, when an arrow is pointing at a small node, it seems that the positioning itself is not reaching the small node. The arrows pointing at the small nodes are assuming the small nodes like the larger nodes. Therefore, there's a space between them.

**To Reproduce**
Having different sized nodes in force graph to compare arrow length between nodes.

**Expected behavior**
All arrows should reach all nodes in the graph.

**Screenshots**
![Force-graph-screenshot](https://user-images.githubusercontent.com/97627324/149208541-f2ad9383-7a31-4bf8-af95-d18d515dda3a.png)

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version 97.0.4692.71

**Comment by vasturiano** [comment]
@angetong thanks for reaching out.

I've tried but am unable to reproduce your issue. Are you using `.nodeVal` to set the different sizes of nodes?
Could you make a simple reproducible example on https://codepen.io that shows the issue?

**Comment by angetong** [comment]
@vasturiano Is it possible to force the links or arrows to be transformed (e.g changing distance from nodes)?

**Comment by vasturiano** [comment]
@angetong you can control it with `linkDirectionalArrowRelPos`.
