### ISSUE TITLE
Draw image on hovered node

### ISSUE THREAD

**Issue by mpn7** [vasturiano/force-graph#259]
Hi,

I'm trying to draw an image when a node is hovered.
I almost got it working but I have some questions.

This is my code:

        ` const N = 20;
		const gData = {
		nodes: [...Array(N).keys()].map(i => ({ id: i, img: "test" })),
		links: [...Array(N).keys()]
			.filter(id => id)
			.map(id => ({
			source: id,
			target: Math.round(Math.random() * (id-1))
			}))
		};

		const elem = document.getElementById('graph');

		const Graph = ForceGraph()(elem)
		.graphData(gData)
		.width($("#graph").parent().width())
		.height(600)
		.nodeLabel('id')
		.nodeAutoColorBy('group')
		.enableZoomPanInteraction(false)
		.onNodeClick(node => {
			// Center/zoom on node
			Graph.centerAt(node.x, node.y, 1000);
			Graph.zoom(2, 2000);
		})
		.onNodeHover(nodeHover =>{
			if(nodeHover){
				Graph.nodeCanvasObject((node, ctx, globalScale) => {
					if(nodeHover.id == node.id){
						console.log("hello")
						const size = 12;
						const img = new Image();
						img.src = "https://dummyimage.com/50x50/000/fff";
						ctx.drawImage(img, node.x - size / 2, node.y - size / 2, size, size);
					}
					
				});
			}
			
		})
		.nodeLabel(node => {})
		.nodeCanvasObjectMode(() => "after")
		.nodeCanvasObject((node, ctx, globalScale) => {
			console.log("hello1")
			const label = node.id;
			const fontSize = 12 / globalScale;
			ctx.font = "${fontSize}px Sans-Serif";
			ctx.textAlign = "center";
			ctx.textBaseline = "middle";
			ctx.fillStyle = "black"; //node.color;
			ctx.fillText(label, node.x, node.y + 10);
		})
	 });`

My first question is: Is it normal that nodeCanvasObject is being called indefinitely? Some times 10 000 times other times 60 000.

My other question is: On hover I'm calling nodeCanvasObject, wich in my understanding is going through all the nodes. Can't I call nodeCanvasObject on just the node that I'm hovering?

My code is missing the part where when you stop hovering, the image disappears and it goes back to normal.

Thank you in advance, any help would be appreciated or any guidance on the best way to do this.

Miguel Neves

**Comment by vasturiano** [comment]
> My first question is: Is it normal that nodeCanvasObject is being called indefinitely? Some times 10 000 times other times 60 000.

Yes this is expected. The canvas is cleared and re-painted at every single frame. That's how the node motion animation is created. Also, the `nodeCanvasObject` method is invoked per every node at every frame. So, it's important that the method is kept as performant as possible to guarantee fluid motion with a good frame rate.

> My other question is: On hover I'm calling nodeCanvasObject, wich in my understanding is going through all the nodes. Can't I call nodeCanvasObject on just the node that I'm hovering?

As mentioned above, that method is invoked for every node. Thus any distinguishing logic between nodes needs to exist inside that method implementation. An alternative approach is to not modify the `nodeCanvasObject` method on hover, but simply change the state of the outer variable `hoverNode`. And then in your static `nodeCanvasObject` method just check against that variable at runtime.
Similar to what happens in the [highlighting example](https://github.com/vasturiano/force-graph/blob/master/example/highlight/index.html).

This will also help fix your other question:

> My code is missing the part where when you stop hovering, the image disappears and it goes back to normal.

**Comment by mpn7** [comment]
Thank you very much for your explanation. I didn't understand how `nodeCanvasObject` worked, and it helped a lot.
