### ISSUE TITLE
New feature request: node and link rendering function on top of default behavior

### ISSUE THREAD

**Issue by davidballester** [vasturiano/force-graph#26]
Hi. First of all, amazing library. I enjoy it a lot.

I'm working on a personal project and found a situation in which I want to customize how the links are rendered (by adding a label), but also want to relay on the default rendering mechanism. 

I thought it could be interesting to be able to specify that my `linkCanvasObject` function is not meant to substitute the link rendering, just to be executed and then proceed with the default rendering. Possibly by returning a boolean, for instance. Or maybe specifying a different prop for that, I haven't thought much about it.

If you think that is something worth doing, I could try and make a PR for it.

**Comment by vasturiano** [comment]
@davidballester thanks for reaching out. I'm glad the lib is useful. :) 

That's an interesting suggestion. I think it could be useful.
I suggest to have an additional `boolean` prop that indicates whether the custom `linkCanvasObject` is intended to extend or replace the default rendering. For example `linkCanvasObjectExtend`.

Using the return value of `linkCanvasObject` is a bit of a hidden behavior and may break backwards compatibility in some user implementations.

And, the same logic should be used for a `nodeCanvasObjectExtend` too.
