### ISSUE TITLE
node text color using 'nodeCanvasObject', ctx.fillStyle is not working

### ISSUE THREAD

**Issue by rajasekar-pb** [vasturiano/force-graph#260]
**Describe the bug**
On changing node text color using 'nodeCanvasObject', the color wont update.

**To Reproduce**
`updateNodeTextColor(Graph, nodeTextColor: string) {
    Graph.nodeCanvasObject((node, ctx) => {
        ctx.fillStyle = nodeTextColor;
    });
}`

**Expected behavior**
up on calling the above function, node text color should update.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 100.0.4896.75 (Official Build) (64-bit)

**Comment by vasturiano** [comment]
@rajasekar-pb thanks for reaching out.

It looks like you're not doing any paint operations in your `nodeCanvasObject` function. You're simply setting the canvas fill color, but not using that for anything.

**Comment by rajasekar-pb** [comment]
`nodeCanvasObject` takes only values on first load of the graph ... whenever we update after the initial load, it shows only the old value ... also i am using the same method to update font size `ctx.font` it is working fine ...

**Comment by rajasekar-pb** [comment]
@vasturiano I have figured it out ... the issue is from myside only ... 

I was using 2 function jumps and a validation method before get to the above mentioned `updateNodeTextColor` function ... the `Graph` param lost it reference and ends with `undefined` value ... 

I have solved it by separating the color update process with minimal validation ... now it works well ... ;)
