### ISSUE TITLE
Big graph loading slow

### ISSUE THREAD

**Issue by lfvrarnaud** [vasturiano/force-graph#264]
Hello

Is your feature request related to a problem? 
We are displaying graphs with well over 100K nodes, but the graph display is slow or never arrives

Describe the solution you want
Is it possible to display the graph directly (or after a loading time) in the final form without animation

thank you in advance for your help

**Comment by vasturiano** [comment]
@lfvrarnaud thanks for reaching out.

That's quite a high volume of nodes. Typically the number of links will be even higher, which is what actually contributes to a large portion of the strain in the system.

In any case, you can easily bypass the graph cooldown phase animation, by setting:
```js
.cooldownTicks(0)
```
But then you need to give the warmup phase (before rendering starts) a number of engine iterations so the graph has a chance to develop, f.e.:
```js
.warmupTicks(60)
```

**Comment by lfvrarnaud** [comment]
Hello 

the solution works perfectly
it remains for me to make a loading animation 

Thanks for your help and this great library
