### ISSUE TITLE
Link length not increasing with node size

### ISSUE THREAD

**Issue by shankarPolitica** [vasturiano/force-graph#265]
**Describe the bug**
When node size increased with nodeRelSize function, the link length is not auto incrementing. We are unable to see the links (the nodes are covering the links).

**To Reproduce**
1. Set nodeRelSize to 17
    `nodeRelSize(17)`
3. Generate graph with some links
4. Observe the graph, we will see links are not visible (links are behind the nodes)

**Expected behavior**
When nodeRelSize increased, the links should properly adjusted according to the node size.

**Screenshots**
 Actual Graph (With nodeRelSize 17)
![image](https://user-images.githubusercontent.com/60752461/167259046-698a6c5b-6302-4051-8a57-81a47269e356.png)

Expected Graph
![image](https://user-images.githubusercontent.com/60752461/167264998-a4f5a912-b41f-4f8f-a9b2-6d8784f86a5a.png)

FYI with nodeRelSize 4, working fine.
![image](https://user-images.githubusercontent.com/60752461/167264657-798621c0-207d-4f1b-8a47-80617ecd5d3d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by vasturiano** [comment]
@shankarPolitica you can update the links distance to your taste via
```js
.d3Force('link').distance(/* your value */)
```

I don't believe automatically updating the links distance based on nodes size is a great idea. It will make the framework less flexible.

**Comment by shankarPolitica** [comment]
It worked.
Thanks @vasturiano

**Comment by zzswang** [comment]
@shankarPolitica 

When the size of the nodes increases, how can the nodes become more sparsely distributed without using a fixed link distance?
