### ISSUE TITLE
nodeCanvasObject autocolor by group

### ISSUE THREAD

**Issue by cmchow07** [vasturiano/force-graph#273]
Dear Sir,

I am using .nodeCanvasObject to draw oval shape for each node. Then I fill in color by ctx.fillStyle. So they are in same color.

May I know is there a built-in method, so they could be autocolor differently by group? (similar to .nodeAutoColorBy)
I don't have color attributes/properties for nodes or in the json file.

Many Thanks,
CM

**Comment by vasturiano** [comment]
@cmchow07 the `nodeAutoColorBy` is meant to be used only with the default representation of the nodes. If you're in custom `nodeCanvasObject` mode you need to maintain your own color map and set it as `fillStyle`.

You could consider using an [ordinal scale from d3](https://github.com/d3/d3-scale#scaleOrdinal) for this purpose.

**Comment by cmchow07** [comment]
I figure it out with the reference. Thank you!
