### ISSUE TITLE
About onLinkClick() or other relevant methods

### ISSUE THREAD

**Issue by cmchow07** [vasturiano/force-graph#276]
Dear Sir,

I am editing the links' feature.

For d3/dagre directed force graph, there is the setEdge() method, that could insert html tag that is dynamic in nature with links' data. When "onclick" on link, a modal table with dynamic data base on links' data could be displayed.

Sample is as below:
g.setEdge(source, target, {
  labelType: "html",
  label: '<a>'+source...type+'</a>'
});

May I know is the similar feature for this library? I am trying to use onLinkClick() but it seems that it could not achieve the similar outcome.

Best Regards,
CM

**Comment by vasturiano** [comment]
@cmchow07 it seems like using `onLinkClick` should give you the event trigger you need to do this. Is `onLinkClick` not firing for you?

**Comment by cmchow07** [comment]
@vasturiano 
I have figured out another work-around. Thank you for your reply.
