### ISSUE TITLE
Change in .nodeLabel/.linkLabel

### ISSUE THREAD

**Issue by cmchow07** [vasturiano/force-graph#278]
Dear Sir,

I have been using this lib for some days.

It seems that the .nodeLabel/.linkLabel have been changed recently?
Instead of tooltip that pop up on nodes/links, it becomes showing the info at the bottom of the page. It's less readable.
May I know how to resume to the previous effect? Or is it a bug?

Regards,
CM

**Comment by vasturiano** [comment]
Thanks for the report @cmchow07! This has now been fixed in the newest version: `1.42.13`.
