### ISSUE TITLE
disable capturing scroll events unless clicked

### ISSUE THREAD

**Issue by wirepair** [vasturiano/force-graph#28]
I'm trying to have my force graph only be zoom-able if a user actively clicks the graph. Right now if i hover over the graph for a period of time, it seems to automatically capture this and forces a user to click outside the graph to be able to scroll the rest of the window. Is there a method I am missing to enable such a feature?

**Comment by vasturiano** [comment]
@wirepair you can use `.enableZoomPanInteraction(<boolean>)` (`true` by default) to enable/disable zoom/pan functionality.

**Comment by wirepair** [comment]
Thanks!
