### ISSUE TITLE
How to positioned node label

### ISSUE THREAD

**Issue by shreykene** [vasturiano/force-graph#288]
How can we set the position of the node label? because when I hover on the bottom positioned node then the label box is getting hide.
Please see the below screenshots to get my problem.

1. When the node is positioned at the center node label will display properly.
![image](https://user-images.githubusercontent.com/37397006/194547413-3ba134a3-0169-41aa-9071-0c2ba3460a53.png)

2. When the node is positioned at the bottom of the page the node label is getting a hide
![image](https://user-images.githubusercontent.com/37397006/194547657-7d0cd5fe-0e3c-4592-b107-8935e1d1b8e9.png)

**Comment by vasturiano** [comment]
Thanks for reaching out @shreykene.

This has now been fixed in the latest version. The vertical orientation of the tooltip is flipped when near the bottom of the canvas, to prevent it from getting hidden.

**Comment by shreykene** [comment]
Thank you @vasturiano now it working properly.
