### ISSUE TITLE
text label shown by default

### ISSUE THREAD

**Issue by zzggyy1** [vasturiano/force-graph#29]
Hello,

I am wondering if it is possible to show node labels next to nodes just like it is the case in sigma.js?

Thank you in advance!

**Comment by vasturiano** [comment]
@zzggyy1 you can extend the current node drawing by setting `.nodeCanvasObjectMode(() => 'after')` and `.nodeCanvasObject((node, ctx) => <draw label code>)`. 

See this [example](https://vasturiano.github.io/force-graph/example/text-nodes/) for an option on drawing node labels: https://github.com/vasturiano/force-graph/blob/master/example/text-nodes/index.html
