### ISSUE TITLE
Accessing the canvas outside force-grapth

### ISSUE THREAD

**Issue by moda20** [vasturiano/force-graph#291]
Is there a way to draw a background image to the whole canvas? Trying to access the canvas from outside using elementId  doesn't work at all. nothing happens in fact.

**Comment by vasturiano** [comment]
@moda20 you can use [onRenderFramePre](https://github.com/vasturiano/three-forcegraph/commit/9dea32fc790dd0644510f13ea4ae0446cf55acb6) to add additional elements to the canvas, such as a background for instance.

**Comment by moda20** [comment]
@vasturiano that's true, I found out about it since I posted this. thanks
