### ISSUE TITLE
onNodeHoverEnd / onNodeMouseout

### ISSUE THREAD

**Issue by oskameDEV** [vasturiano/force-graph#292]
I don't see a way to detect when the cursor leaves a node after entering it.

A way to bind a function to this event would be very useful.

**Comment by vasturiano** [comment]
@oskameDEV it's the same method (`onNodeHover`). It passes `null` as a param when hovering off onto the background.
From the docs:

> Callback function for node mouse over events. The node object (or null if there's no node under the mouse line of sight) is included as the first argument, and the previous node object (or null) as second argument: onNodeHover(node, prevNode).

**Comment by oskameDEV** [comment]
Ah I misunderstood how that worked then. Thank you for responding so fast.

Here's a barebone example for anyone else looking for how.
`.onNodeHover(node => {
     if (node){
          // ON MOUSE ENTER
     }
     else {
          // ON MOUSE LEAVE
     }
}`
