### ISSUE TITLE
Can I customize a color gradient link 

### ISSUE THREAD

**Issue by liuguanyu** [vasturiano/force-graph#296]
Hello.

There is a orange node and a blue node on the canvas. I want to  customize a color gradient link, from blue to orange, using force-graph. just like the following pictures：

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1177489/203718252-db6b67d7-0e91-4e58-bf63-9e4434e3b5ce.png"> 

These are the nodes.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1177489/203718330-a1896563-1d61-431f-8061-fee2106f6071.png" style="transform:rotate(180deg)">

The above is the link.

Is it possible to customize the color gradient link？

Thanks a lot.

**Comment by vasturiano** [comment]
@liuguanyu you can use `linkCanvasObject` to customize the style of your links in whichever way you'd like. For example to add a gradient to the line. Essentially you issue canvas paint commands, so if something is possible in canvas it should be possible here.

You can look into [createLinearGradient](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createLinearGradient) to achieve this.

**Comment by liuguanyu** [comment]
> @liuguanyu you can use `linkCanvasObject` to customize the style of your links in whichever way you'd like. For example to add a gradient to the line. Essentially you issue canvas paint commands, so if something is possible in canvas it should be possible here.
> 
> You can look into [createLinearGradient](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createLinearGradient) to achieve this.

Thanks
