### ISSUE TITLE
WebGL 3D version vs force-graph 

### ISSUE THREAD

**Issue by peekxc** [vasturiano/force-graph#3]
Hi @vasturiano, 

I love your project, especially the nice concise and useful API. 

What's the difference between this project and using the other [3-D force graph](https://github.com/vasturiano/3d-force-graph) project with _numDimensions = 2_? I see this one uses a canvas renderer, and the other uses ThreeJS which in turn uses WebGL, but I though ThreeJS also uses a canvas renderer backup? 

The feature-set of the 3D version looks almost the same as the 2D version. 

Edit: To be more specific, could I simply use the 3d-force w/ _numDimensions = 2_ to achieve a nice WebGL-based 2d force rendering?

**Comment by vasturiano** [comment]
Hi @peekxc, thanks for reaching out. This is a great question. The answer is that the `numDimensions` property relates to how many dimensions to run the **force simulation** engine on. While the distinction between this library and `3d-force-graph` relates to the spatial environment where the objects are drawn.
So, in `force-graph` you always have a two-dimensional force-simulation in a two-dimensional environment. In `3d-force-graph` you have a three-dimensional space with the possibility of a 1, 2 or 3D force-simulation. 

This [example](https://bl.ocks.org/vasturiano/f59675656258d3f490e9faa40828c0e7) shows what those different possibilities look like.

So yes, you can have `3d-force-graph` running a force-simulation in 2D, but keep in mind the spatial navigation (zoom / pan) would still be in 3D.

**Comment by peekxc** [comment]
Ahh I see the distinction, thanks for the clarification! In that case thank you for making this, as I'm only concerned with graphs drawn within a 2D environment. 

I look forward to where this package goes!

**Comment by vasturiano** [comment]
Hi @peekxc.

1. `force-graph` is already using Canvas/WebGL as rendering element, with a [2d context](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D).

2. You can find some methods in the component interface that allow you to manipulate the d3 force engine configuration, like `d3AlphaDecay`, `d3VelocityDecay` and `d3Force`. It's not as low level as [d3-force](https://github.com/d3/d3-force) but that is also the purpose of the library, to provide a higher level abstraction.

**Comment by peekxc** [comment]
1. Right... I guess I saw it was using my CPU intensively, so I assumed it wasn't using the GPU, but honestly I don't know much about the internals, so I'll defer to your expertise

2. I mean the [simulation object](https://github.com/d3/d3-force#forceSimulation), not just the [force engine](https://github.com/d3/d3-force#simulation_force). I do appreciate the higher level abstraction very much :)
