### ISSUE TITLE
nodeLabel displaying wrong node

### ISSUE THREAD

**Issue by joshraymo** [vasturiano/force-graph#303]
**Describe the bug**
There seems to be a bug where the incorrect node is passed to our nodeLabel function on mouse over.  As you can see in the attached video, it only occurs when hovering over the outer border.

**To Reproduce**
1. Hover 

**Expected behavior**
The nodeLabel behavior should not display the incorrect node information

**Smartphone (please complete the following information):**
 - Device: Mac Mini (M1 chip)
 - IOS 13.1
 - Chrome
 - react-force-graph-2d 1.23.8

**Additional context**
We are using a custom function passed to nodeLabel that injects an html template string

```
  const generateTooltip = (node) => {
    console.log('node: ', node, nodeMap);
    if (urlParams.org_level !== 'individual' && node.email) {
      return;
    }
    let tooltip = `<div style="background-color: ${global.color.text_background}; position: absolute; left: 0px; top: 0px; padding-top: 16px; padding-bottom: 40px; display: flex; flex-direction: column; flex-wrap: nowrap; justify-content: flex-start; box-shadow: 0px 2px 1px -1px rgb(0 0 0 / 20%), 0px 1px 1px 0px rgb(0 0 0 / 14%), 0px 1px 3px 0px rgb(0 0 0 / 12%)">`;
    let tooltipLeft = `<div style="white-space: nowrap; padding-left: 16px; display: flex; flex-direction: column; justify-content: flex-start;">`;
    let tooltipRight = `<div style="white-space: nowrap; padding-left: 4px; padding-right: 16px; display: flex; flex-direction: column; justify-content: space-around;">`;
    const addedFields = [];
    const { x, y } = fgRef.current?.graph2ScreenCoords(node.x, node.y);
    tooltipFields.forEach((item) => {
      const propertyToCheck = node[item[0]] || '';
      if (propertyToCheck) {
        if (!addedFields.find((obj) => obj === item[1])) {
          addedFields.push(item[1]);
          if (item[1] === 'Name') {
            tooltip += `<div style="padding-left: 16px; padding-right: 16px; padding-bottom: 16px;"><b style="color: ${
              global.color.black
            }; font-size: 16px; font-family: Roboto;">&nbsp;${node[item[0]]}</b></div>`;
          } else {
            tooltipLeft += `<div><b style="color: ${global.color.black}; font-size: 12px; font-family: Roboto;">&nbsp;${item[1]}&nbsp;</b></div>`;
            tooltipRight += `<div style="color: ${global.color.black}; font-size: 12px; font-family: Roboto;">${
              node[item[0]]
            }&nbsp;</div>`;
          }
        }
      }
    });
    tooltipLeft += `</div>`;
    tooltipRight += `</div>`;
    const temp = `<div style="display: flex;">${tooltipLeft}${tooltipRight}</div>`;
    tooltip += `${temp}</div>`;
    return tooltip;
  };
```

https://user-images.githubusercontent.com/86807954/214177991-3b793580-8aab-47c1-9e91-1dfcba5be497.mov

**Comment by vasturiano** [comment]
@joshraymo thanks for reaching out.

This is caused by a rare conflict of pixel color antialiasing, typically happening at the edge of curved shapes. It's an unfortunate side effect of the method used to detect mouse hover events, which uses [canvas-color-tracker](https://github.com/vasturiano/canvas-color-tracker). 

The readme in that repo explains most of the motivation for this method. What happens is in rare cases even though there is a checksum checking the unique indexes, collisions might still occur, which is what you're experiencing in your example.

**Comment by joshraymo** [comment]
@vasturiano Thank you for the response!
