### ISSUE TITLE
Simple way to force redraw?

### ISSUE THREAD

**Issue by bubblegumsoldier** [vasturiano/force-graph#308]
**Is your feature request related to a problem? Please describe.**
I have implemented a custom box selection. The selection of a node is displayed in my custom draw function, meaning if it is displayed I will overlay a border. But during dragging it doesnt consistently update the drawing. Is there a way to force a redraw of nodes on each mouse move?

**Describe the solution you'd like**
A simple `Graph.redraw()` method would be great!

**Describe alternatives you've considered**
I considered setting the data on every mouse move, that works but it will lead to destabilization, so that the selection will start a new stabilization process, making it "bounce away" when I select a node.

**Additional context**
...

**Comment by vasturiano** [comment]
@bubblegumsoldier thanks for reaching out.

Are you drawing your node border inside the `.nodeCanvasObject` function? If so, it should consistently update at every frame, and keep up with the node's style reliable.

Would you be able to make a simplified example on https://codepen.io/ if you're still having an issue?

**Comment by bubblegumsoldier** [comment]
https://codepen.io/bubblegumsoldier-the-decoder/pen/MWqvwzo

I recreated it in a simple way, but it takes some patience to get to the "failing" state. I added a small note at the top on one way to force it. If you play around enough you will realize it does not **reliably** refresh the state.

**Comment by bubblegumsoldier** [comment]
`.autoPauseRedraw(false)` seems to fix the issue!
