### ISSUE TITLE
Remember color groups in autoColorObjects

### ISSUE THREAD

**Issue by stefanprobst** [vasturiano/force-graph#31]
Currently, [`autoColorObjects` does not store the colors auto-assigned to categories in state](https://github.com/vasturiano/force-graph/blob/998e2b3453869a68f32b3a36e5dc69ebaab1ea57/src/color-utils.js#L12). When incrementally adding nodes to the graph, new categories will therefore be assigned a color already in use by a different type.

**Comment by vasturiano** [comment]
Thanks for the issue. It's been fixed in `v1.16.4`.
