### ISSUE TITLE
Connection of the two examples Load JSON and Images as nodes

### ISSUE THREAD

**Issue by cherno-alpha** [vasturiano/force-graph#321]
Hello vasturiano, first of all thank you very much for your outstanding work on the topic of graph drawing.

Is there any way to create a graph that has images as nodes but uses a custom graph created with JSON?

Unfortunately I fail trying to combine the two example files and don't know what to do.

With the Load JSON example I have managed to create my own graph. In the Images as nodes example, I can change the path and display custom images, but fail when trying to import the custom graph with JSON.

Please, i need your help!

Best regards from Germany
Dennis

**Comment by vasturiano** [comment]
@cherno-alpha thanks for reaching out.

The two features are completely independent. To better understand the issue you're experiencing, it's easier if you could create a small example on https://codepen.io/ that reproduces the problem.

**Comment by cherno-alpha** [comment]
I'm new to github and codepen, so a cautious heads up.

I used your Load JSON example and want to set images as nodes with nodeCanvasObject(). What do I need to write in the function?

Here is the Link to Codepen:
https://codepen.io/cherno-alpha/pen/oNamadd

**Comment by vasturiano** [comment]
@cherno-alpha you just need to refer to this example to see how to write your canvas code to paint images:
https://github.com/vasturiano/force-graph/blob/06e372da6a02b838395e7b85c26fd05d5e63d31c/example/img-nodes/index.html#L32-L35

**Comment by KyleDave** [comment]
@cherno-alpha - this was exactly what I wanted to ask!   The JSON fetch is what I need for a large family tree:
https://quickening.zapto.org/fg-network.html
But I want images on the nodes, with attached labels:
https://quickening.zapto.org/fg-images.html

I can see the network example creating a data object with methods that refer to "node object accessor", but I don't know how to change nodeCanvasObject to work with that data object.  It just tells me img undefined:

`fetch('Tree/links.json').then(res => res.json()).then(data => {
            
      const Graph = ForceGraph()
      (document.getElementById('graph'))
      .nodeCanvasObject(({ img, x, y }, ctx) => {
        const sizeX = 200;
        const sizeY = 237;
        const url = img.currentSrc;
        const label = decodeURI(url.substring(url.lastIndexOf('/')+1).slice(0, -4));
        const textWidth = ctx.measureText(label).width;
        ctx.drawImage(img, x - sizeX / 2, y - sizeY / 2, sizeX, sizeY);
        ctx.font = "11px Arial";
        ctx.fillText( label, x - sizeX / 2 + ( sizeX / 2  - textWidth / 2), y + sizeY / 2 + 20);
      })
`
I'm guessing "{img, x, y}" is the node object...

**Comment by vasturiano** [comment]
@KyleDave yes that is the node object. So, basically you first need to add your image objects to each of your nodes, under the `img` attribute. This example shows that:
https://github.com/vasturiano/force-graph/blob/06e372da6a02b838395e7b85c26fd05d5e63d31c/example/img-nodes/index.html#L12-L21
