### ISSUE TITLE
How to get the canvas element of a force-graph instance? 

### ISSUE THREAD

**Issue by GwokHiujin** [vasturiano/force-graph#322]
Hello, this project is really excellent and useful! Thank you very much for developing it. ✨ 

I'm recently deploying it in my own project and trying to add an "export as image" feature to it. Since the image is rendered in a canvas element, I think I need to use a method like toDataURL to do the export, but I can't find a corresponding interface that allows me to get the canvas element in the page. Is there a method I can call?

**Comment by vasturiano** [comment]
@GwokHiujin thanks for reaching out.

If you have a reference to the DOM element where you mounted the graph (f.e. `myElem`), you can simply query for a child `canvas` element, like so:
```js
myElem.querySelector('canvas')
```

**Comment by GwokHiujin** [comment]
> @GwokHiujin thanks for reaching out.
> 
> If you have a reference to the DOM element where you mounted the graph (f.e. `myElem`), you can simply query for a child `canvas` element, like so:
> 
> ```js
> myElem.querySelector('canvas')
> ```

Thank you for your reply! This solves my problem nicely :)
