### ISSUE TITLE
Part of data caption in node

### ISSUE THREAD

**Issue by bennie84** [vasturiano/force-graph#33]
Hi, 

First off i would like to say that i really like this libary :) The visualisation look amazing. That said i was wondering if it's possible to display the data caption, partial in the node? Like this image:
![image](https://user-images.githubusercontent.com/39337564/58807071-b032cd80-8617-11e9-8483-7689620b7aeb.png)

 I'm using this code:

session
      .run('MATCH (n)-->(m) RETURN { id: id(n), label:head(labels(n)), caption:n.title } as source, { id: id(m), label:head(labels(m)), caption:m.title } as target LIMIT $limit', {limit: 1000})
      .then(function (result) {
        const nodes = {}
        const links = result.records.map(r => { 
	       var source = r.get('source');source.id = source.id.toNumber();
           nodes[source.id] = source;
	       var target = r.get('target');target.id = target.id.toNumber();
           nodes[target.id] = target;
	       return {source:source.id,target:target.id};
		    	    });
        session.close();
        console.log(links.length+" links loaded in "+(new Date()-start)+" ms.")
        const gData = {nodes: Object.values(nodes), links: links}
        const Graph = ForceGraph()(elem)
                      .graphData(gData)
					  .backgroundColor('#ffffff')
					  .nodeLabel(node => `${node.label}: ${node.caption}`)
                      .onNodeHover(node => elem.style.cursor = node ? 'pointer' : null)
                      .nodeAutoColorBy('label')
         .nodeCanvasObjectMode(() => 'after') 
		 .nodeCanvasObject((node, ctx) => 'label')
		 .nodeCanvasObject((node, ctx, globalScale) => {
          const label = node.caption;
          const fontSize = 12/globalScale;
          ctx.font = `${fontSize}px Sans-Serif`;
          const textWidth = ctx.measureText(label).width;
          const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding
          ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
          ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y - bckgDimensions[1] / 2, ...bckgDimensions);
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillStyle = node.color;
          ctx.fillText(label, node.x, node.y);
        });
    });

**Comment by vasturiano** [comment]
@bennie84 this should be quite doable if you write the code to do the text ellipsis in the `nodeCanvasObject`, as it seems you're already doing. 
Does your example work as expected? Feel free to post a [codepen](https://codepen.io/) for reference.

**Comment by aoloo** [comment]
@vergeten do you have an example of this? I would also like to add elipsis for long text.
