### ISSUE TITLE
Conditional node styling based on data values/accessor method (i.e. circles for person, squares for place)

### ISSUE THREAD

**Issue by jacoblindgren** [vasturiano/force-graph#331]
I'm wondering the best way to style a node based on its data value/accessor method (if I understand the latter correctly). For example if my node data is structured like this:

```
"id": "1",
"name": "Leon",
"val": 1,
"color": "#8fccb3",
"type": "person"
```

With `type` sometimes set to `person` and other times `place`, what is the best way to change a node's color or shape based on the value? I managed to do this for nodeColor:

`.nodeColor(d => d.type=="person" ? '#8fccb3' : '#22322c')`

but it only caters to two possibilities, and would break if I were to introduce a third `type` (like `thing`). Is it possible to use something like an `if` statement? Conditionally changing `nodeCanvasObject` seemed more complicated and I couldn't wrap my head around, but I'd also like to use different shapes (and sometimes an image) also based on the `type` value.

Any suggestions are much appreciated!

**Comment by vasturiano** [comment]
@jacoblindgren you can easily use an if statement, or any other other JS you like inside that method. It's just a regular JS function. F.e.:
```js
.nodeColor(d => {
  if (d.type === "person") {
    return '#8fccb3';
  } else { ... }
})
```

**Comment by jacoblindgren** [comment]
Thank you!
