### ISSUE TITLE
mousedown event not working after adding it

### ISSUE THREAD

**Issue by jiangzhenxiang** [vasturiano/force-graph#332]
**Describe the bug**

I am trying to add a mousedown event to the vasturiano/force-graph library, but it does not seem to work as expected. Here are the steps to reproduce the issue:

**To Reproduce**

```
      const canvas = elem.querySelector('canvas')
      console.log('-> canvas', canvas)
      const ctx = canvas.getContext('2d')
      console.log('-> ctx', ctx)

      canvas.addEventListener('mousedown', (event) => {
        console.log('-> mousedown', event)
      })
```
**Expected behavior**
The mousedown event should trigger when I click on a node in the force graph.

Please let me know if there are any specific details or code examples you need to further investigate this issue. Thank you for your assistance!

**Comment by vasturiano** [comment]
@jiangzhenxiang please look into the built-in pointer interaction methods on this module:
https://github.com/vasturiano/force-graph#interaction

**Comment by jiangzhenxiang** [comment]
> pointer

thanks
