### ISSUE TITLE
How to draw nodes around a circle

### ISSUE THREAD

**Issue by willpinha** [vasturiano/force-graph#338]
Hey, do you have any idea of how to implement the following graph using force-graph?

![image](https://github.com/vasturiano/force-graph/assets/86596621/bb314bd3-63e6-4af8-b602-43bd49b9ef78)

**Comment by vasturiano** [comment]
@willpinha it's possible, but since it's not exactly a force-directed graph you might have better luck using a chord diagram layout, such as [d3-chord](https://github.com/d3/d3-chord): https://observablehq.com/collection/@d3/d3-chord

**Comment by willpinha** [comment]
I didn't know D3 had a solution for this. Thanks!
