### ISSUE TITLE
Highlight nodes and its neighbors

### ISSUE THREAD

**Issue by soccerdroid** [vasturiano/force-graph#34]
Hello! Great library with great performance. I was wondering if there is a way in which I can access to the neighbors of a node when hovering over a node. I a seeking to highlight all the neighbors and links, and achieve this effect: http://plnkr.co/edit/3fv3IR3S3Kp86rAummnz?p=preview

**Comment by vasturiano** [comment]
Hi @soccerdroid. You can simply traverse the graph structure and apply styling to neighbors on hover events. Here's an example that does something similar to that:
https://bl.ocks.org/vasturiano/321a770c3f4b041d1a4f40f1f4ecbb6c

**Comment by soccerdroid** [comment]
Thank you sir! I am working with Creative Commons in visualizing their licensing content (CC-Catalog).  We are using your library. I'll let you know about our final result

**Comment by soccerdroid** [comment]
Closing this issue...
