### ISSUE TITLE
click/drag not registering

### ISSUE THREAD

**Issue by sakgoyal** [vasturiano/force-graph#357]
**Describe the bug**
I am using the basic demo and I noticed that the clicking/drag behavior is strange. I can't click/drag on some nodes, but I can on others. some of them will drag the whole graph, some will actually move independently. why is this happening and is this something I can fix?

it seems arbitrary which ones I can and cannot move, which makes me believe this is a bug and not intended

**To Reproduce**
1. Go to basic example
2. drag some node
3. drag modes the whole graph (pans the graph)
4. drag another node (move individual node)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Brave

**Comment by vasturiano** [comment]
@sakgoyal thanks for reaching out.

Since you're using Brave, your issue might be related to this one: https://github.com/vasturiano/force-graph/issues/177
