### ISSUE TITLE
Use predefined coordinates for nodes

### ISSUE THREAD

**Issue by havardl** [vasturiano/force-graph#38]
Hi,

I'm working with a fairly large graph (22K nodes and 70K edges) and I'm trying to find the best way of rendering it in the browser. So far I've tried both D3 and Sigma.js, with sigma performing the best, but still with a lot of lag when interacting with the graph. 

I tested my data with this component, and it looks promising, but because it's computing the layout it takes too long for my use case. But since my data already includes x and y coordinates for the nodes, I was wondering if it's possible to use the component to render the graph without a iterative layout? Maybe I missed this in some of the examples, but they all seemed to use a computed layout. 

Thanks for a great component!

**Comment by vasturiano** [comment]
@havardl thanks for reaching out. You can attribute coordinates to nodes by setting `x` and `y` attributes in each of the node objects. The framework will respect that as their starting positions.
Then I would recommend setting `cooldownTicks(0)` which will tell the force engine to to not run any iterations. This should make your nodes layout fixed.

**Comment by soccerdroid** [comment]
Hello! I also have a large graph (47k nodes and links). May I know @havardl  what results/improvements did you get with the suggestions made by @vasturiano ?

**Comment by havardl** [comment]
Hey @soccerdroid, I actually ended up going back to my original implementation with Sigma.js for this specific task after figuring out how to turn of edges rendering which decreased the rendering time of the graph. 

But I assume importing the nodes with `x` and `y` coordinates in the json file and then updating the node objects would work just as well here.

**Comment by soccerdroid** [comment]
> Hey @soccerdroid, I actually ended up going back to my original implementation with Sigma.js for this specific task after figuring out how to turn of edges rendering which decreased the rendering time of the graph.
> 
> But I assume importing the nodes with `x` and `y` coordinates in the json file and then updating the node objects would work just as well here.

Thank you @havardl . If possible, could you give me a hint of the algorithm you used for calculating the nodes positions?
