### ISSUE TITLE
Multigraph support? (loops and multi-edges)

### ISSUE THREAD

**Issue by mkhorton** [vasturiano/force-graph#4]
I couldn't see a mention of this in the documentation. Does force-graph support multiple edges / self-loops? If not, are there any plans to add support? This would be really useful!

(See top figure on https://en.wikipedia.org/wiki/Multigraph for an example of this kind of visualization)

**Comment by vasturiano** [comment]
@mkhorton thanks for the request! With `v1.4.0`, I just added a new property `linkCurvature` that lets you render curved lines, to support easy representation of multigraphs and other cases where it's important to separate links visually. Here's an example: https://vasturiano.github.io/force-graph/example/curved-links/

Let me know if this works out for you.

**Comment by mkhorton** [comment]
Thanks very much for adding this! This is excellent
