### ISSUE TITLE
How can use context menu on node click?

### ISSUE THREAD

**Issue by gdswapnil11** [vasturiano/force-graph#40]
Hello  am using force-graph in my project and need to use context menu on node click, how how do i get that or any alternative ways to do so. thanks .

**Comment by vasturiano** [comment]
@gdswapnil11 you have access to left and right click node events via `onNodeClick`, `onNodeRightClick`. 
Managing a context menu is outside of the scope of this module. But if you don't want to implement it from scratch you should be able to find a third-party module that can be triggered by the above events and help you manage the context menu interaction, for example: https://github.com/patorjk/d3-context-menu

**Comment by gdswapnil11** [comment]
hey @vasturiano  i write somthing like this but got error.
`d3Force('contextmenu', d3.contextMenu(this.menu))`
i tried this also,
`.onNodeRightClick(d3.contextMenu(this.menu))`
