### ISSUE TITLE
Create nodes on click

### ISSUE THREAD

**Issue by davide-perez** [vasturiano/force-graph#42]
Thank you very much for the excellent features!
In the docs, there are many event listeners for what concerns nodes and links interactions. However, I see no similar container events for what concerns the graph area on which the components are rendered.
Is there any way to trigger events tied to the graph container, such as creating a node on mouse click with specific coordinates (for example accessing the underlying graph canvas)?

**Comment by vasturiano** [comment]
@davide-perez thanks for reaching out. If you'd like to setup event handlers for canvas clicks, you can do it directly on the DOM element that you use to render the graph. For example:
```
myDomElement.addEventListener('click', ev => addNode());
```

The implementation of `addNode` is up to you. You can also extract mouse click coordinates from the event object, if you'd like.

**Comment by davide-perez** [comment]
Thank you for your reply and for the explanation, this definitely solves my issue!
