### ISSUE TITLE
[Question] Set forceLink via d3Force

### ISSUE THREAD

**Issue by vincedani** [vasturiano/force-graph#43]
I would like to set link forces through d3Force option. The edges have types and I would like to set different link forces to different link types as the [README](https://github.com/vasturiano/force-graph#force-engine-d3-force-configuration) describes: `d3Force(str, [fn])`

So my code looks like this: 

```js
(document.getElementById('canvas'))
  ...
  .d3Force('link', link => isHighPriorityEdge(link.type) ? 25 : 2)
```

When I load the page, I get JavaScript error, that id.x is not a function.
Have I missed something or how can I set different forces to different links?

**Comment by vasturiano** [comment]
@vincedani thanks for reaching out.

The 2nd argument of `d3Force` should be a d3 force plugin function, like [this](https://github.com/d3/d3-force/blob/master/src/x.js) for example.

The function you specified is not a force plugin. It seems like you're trying to set the [distance](https://github.com/d3/d3-force#link_distance) property of the existing link force. If so, you can do it as such:
```
.d3Force('link').distance(link => isHighPriorityEdge(link.type) ? 25 : 2)
```

**Comment by vincedani** [comment]
Thank you @vasturiano, it works properly with your solution.
