### ISSUE TITLE
can we use different marker other than arrow?

### ISSUE THREAD

**Issue by gdswapnil11** [vasturiano/force-graph#44]
hey @vasturiano can you tell me how can i use different marker icon instead of arrow.

**Comment by vasturiano** [comment]
@gdswapnil11 you can implement your own custom marker paint function using `.linkCanvasObject()`. Possibly setting `.linkCanvasObjectMode(() => 'after')` you you'd like to keep the current line.

If you're curious as to the current implementation of the arrow paint, it's here: https://github.com/vasturiano/force-graph/blob/master/src/canvas-force-graph.js#L264

**Comment by gdswapnil11** [comment]
![image](https://user-images.githubusercontent.com/23716082/60940866-a5e0af00-a2fa-11e9-9bfa-24e9ad160f9b.png)
