### ISSUE TITLE
Getting exception while use force-graph

### ISSUE THREAD

**Issue by somu2324** [vasturiano/force-graph#47]
**Describe the bug**
I am facing below exception when I try to use sample example.

Uncaught TypeError: selection.interrupt is not a function
    at Function.zoom.transform (vendor.js:136361)
    at Function.zoom.translateBy (vendor.js:136390)
    at adjustCanvasSize (vendor.js:137694)
    at Function.init (vendor.js:138036)
    at initStatic (vendor.js:150687)
    at comp (vendor.js:150681)
    at Class.drawNetworkView (vendor.js:605158)
    at Class.didInsertElement (vendor.js:605135)
    at Class.trigger (vendor.js:67828)
    at Class.superWrapper [as trigger] (vendor.js:65474)

**To Reproduce**
I just copy the sample code and try to launch graph view but not able to see any thing due to exception. 

I am able to see view when I try to hit yours link
https://vasturiano.github.io/force-graph/example/basic/ 
<img width="986" alt="Screen Shot 2019-08-14 at 3 36 08 PM" src="https://user-images.githubusercontent.com/52206615/63013697-6df4fa80-beaa-11e9-9c0a-6d4c5515f5bb.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

my sample code attached here.
in my templlate.hbs file I've declared div 
and
in my js file I've write below method.
drawNetworkView () {

    const N = 80;
    const gData = {
      nodes: [...Array(N).keys()].map(i => ({ id: i })),
      links: [...Array(N).keys()]
        .filter(id => id)
        .map(id => ({
          source: id,
          target: Math.round(Math.random() * (id-1))
        }))
    };
    const NODE_R = 8;
    let highlightNodes = [];
    let highlightLink = null;
    const elem = document.getElementById('graph');
    window.ForceGraph()(elem)
      .graphData(gData)
      .nodeRelSize(NODE_R)
      .onNodeHover(node => {
        highlightNodes = node ? [node] : [];
        elem.style.cursor = node ? '-webkit-grab' : null;
      })
      .onLinkHover(link => {
        highlightLink = link;
        highlightNodes = link ? [link.source, link.target] : [];
      })
      .linkWidth(link => link === highlightLink ? 5 : 1)
      .linkDirectionalParticles(4)
      .linkDirectionalParticleWidth(link => link === highlightLink ? 4 : 0)
      .nodeCanvasObjectMode(node => highlightNodes.indexOf(node) !== -1 ? 'before' : undefined)
      .nodeCanvasObject((node, ctx) => {
        // add ring just for highlighted nodes
        ctx.beginPath();
        ctx.arc(node.x, node.y, NODE_R * 1.4, 0, 2 * Math.PI, false);
        ctx.fillStyle = 'red';
        ctx.fill();
      });

  }

**Comment by vasturiano** [comment]
@somu2324 are you per chance bundling your application with webpack or similar, and have a dependencies lock file? 
If so, you may want to deduplicate `d3` modules to make sure there's only one version of each dependency.

**Comment by somu2324** [comment]
Thanks @vasturiano  , after updation the version I am good to go. :)
