### ISSUE TITLE
Default position of nodes on canvas

### ISSUE THREAD

**Issue by somu2324** [vasturiano/force-graph#48]
**Is your feature request related to a problem? Please describe.**
By default in the graph view, nodes would take its own positions.  I want to place each node at particular place. 

for example by default my graph view look link as shown in attachment "view 1" but I want my default view would be as show in attachment "view 2"

How can I achieve this?
<img width="784" alt="view 1" src="https://user-images.githubusercontent.com/52206615/63375663-d7dd3a80-c3a9-11e9-915d-e7bb91bdeedf.png">
<img width="784" alt="view 2" src="https://user-images.githubusercontent.com/52206615/63375673-dca1ee80-c3a9-11e9-926b-f876dff6f4b2.png">

  
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vasturiano** [comment]
@somu2324 you can add `fx` and `fy` attributes to your node objects. This will fix them to specific coordinates on the canvas and will remain untouched by force directed engine.
