### ISSUE TITLE
issue with zoom 

### ISSUE THREAD

**Issue by somu2324** [vasturiano/force-graph#49]
**Describe the bug**
I want to change node drawing after some level of zoom. For this I want to set some threshold level for zoom.  
is there any way to set zoom threshold level

on solution I thought that, if some how I can get the zoom level then I can check that zoom level with my threshold value but problem is how do I get current zoom level. 

Also please let me know how can I get onwheel event on graph view.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vasturiano** [comment]
@somu2324 there's a few methods you can use for this purpose. 

```onZoom(({ x, y, k }) => ...)``` will let you detect pan/zoom events. From here you can detect if the zoom level is outside your desired range. 
If so, you can call `.zoom(<level>)` to set it back to your max value.
