### ISSUE TITLE
"Invalid attempt to destructure non-iterable instance" error massage Showing.

### ISSUE THREAD

**Issue by gdswapnil11** [vasturiano/force-graph#58]
hey @vasturiano, If i am adding more then 260 nodes on canvas it shows "_Invalid attempt to destructure non-iterable instance_" error and "_Cannot create property 'vx' on string '#223:21'_ "('#223:21 is internal id of node')

**Comment by vasturiano** [comment]
@gdswapnil11 I don't think this would be due to the number of nodes, but it's hard to tell without more context. Can you post an example that replicates you issue, on codepen or so?
