### ISSUE TITLE
How can I reduce link distance between nodes.

### ISSUE THREAD

**Issue by gdswapnil11** [vasturiano/force-graph#59]
![image](https://user-images.githubusercontent.com/23716082/65309730-4a5c5880-dbaa-11e9-86f2-3865b71b934c.png)

**Comment by vasturiano** [comment]
@gdswapnil11 you can configure the `distance` parameter in the link force. Like so:
```
myGraph.d3Force('link').distance(link => /* your code */)
```

See the documentation here: https://github.com/d3/d3-force#link_distance
