### ISSUE TITLE
motion warning for move-viewport example?

### ISSUE THREAD

**Issue by micahstubbs** [vasturiano/force-graph#6]
the control you have over the camera in the move-viewport example is pretty cool. 

that said, this particular example made me feel a bit seasick after a couple rotations (a few seconds of watching) https://github.com/vasturiano/force-graph/blob/master/example/move-viewport/index.html

perhaps we could add a `README.md` to the examples directory https://github.com/vasturiano/force-graph/tree/master/example

that warned new people about the motion in the move-viewport example

**Comment by vasturiano** [comment]
Thanks for bringing that up @micahstubbs. 
I think perhaps that example is just not well achieved in demonstrating the zoom/pan feature. The circular motion is a bit disturbing. Let me think about a better way to feature that method.
