### ISSUE TITLE
Please add clickOnVacantSpace interaction

### ISSUE THREAD

**Issue by wunaidage** [vasturiano/force-graph#61]
https://github.com/vasturiano/force-graph/blob/c71608f07f5fd7a2938006e5d974b93c9e3bfef8/src/force-graph.js#L401
the code seems needed to be added here and some other places.
is it possible I can contribute?

**Comment by vasturiano** [comment]
@wunaidage you can simply detect click events on your DOM element. Background clicks will bubble up the DOM and can be detected upstream.

**Comment by wunaidage** [comment]
well, I tried. Clicking on node and link will always be triggered before the dom click. What I was doing is to click on node to highlight node and click on outside to cancel highlight. But when I add listener on DOM, I cannot even highlight the node anymore. It turns out that it was highlighted first by force-graph and then cancelled by dom click.

**Comment by wunaidage** [comment]
I think the lib is adding click listener on the canvas but I'm adding listener on the container which cause that sequence

**Comment by vasturiano** [comment]
@wunaidage I've just added two methods to help you with handling these cases:
```
graph
  .onBackgroundClick(() => ...)
  .onBackgroundRightClick(() => ...)
```

Make sure to pull the latest version (`1.20.0`).

**Comment by wunaidage** [comment]
wow!! thanks a lot!!!

**Comment by joric** [comment]
@wunaidage how can I change cursor from hand to arrow? I may need to disable the hand sometimes. Set the handler dynamically or something?

**Comment by vasturiano** [comment]
@joric the cursor is changing to pointer because the background is clickable. That is indicated by defining a handler for `onBackgroundClick`.

It's not recommended but if you want you could override that styling by forcing `cursor: default` on css, everytime a node's hover is completed, i.e. `onNodeHover(node => !node && /* your code */)`.

**Comment by joric** [comment]
@vasturiano I had to use timeout like this, delay shouldn't be too large or it affects the nodes:
```js
.onNodeHover(node => !node && (setTimeout(()=>document.querySelector('canvas').classList.remove('clickable'),1)))
```
