### ISSUE TITLE
Text as Nodes doesn't allow for .nodeColor()

### ISSUE THREAD

**Issue by mking4** [vasturiano/force-graph#62]
I'm trying to use the "text as nodes" example listed in the documentation. However, when I replace .nodeAutoColorBy('group') with .nodeColor(), the text is white and unreadable regardless of what color I attempt to input.

**Comment by vasturiano** [comment]
@mking4 in that example `.nodeAutoColorBy('group')` is simply adding an additional attribute to the nodes called `color`, generated automatically from the node's `group` attribute.
The color setting is up to you inside the `nodeCanvasObject` method, and you can use any color you'd like as `ctx.fillStyle`.
