### ISSUE TITLE
The layout is broken for the basic example code

### ISSUE THREAD

**Issue by hsluoyz** [vasturiano/force-graph#63]
**Describe the bug**

The final layout of the graph is nearly broken when I try the basic example with my data.

**To Reproduce**
1. Use my HTML code.
2. Load a graph with 5000 nodes and 5000 edges.
3. Use Chrome to browser the HTML.

**Expected behavior**

A beautiful graph

**Screenshots**

The final layout looks like this:

![image](https://user-images.githubusercontent.com/3787410/66025407-f8f88580-e528-11e9-86b8-b38028267669.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome 77
- UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Additional context**

My script:

```html
<head>
    <style> body { margin: 0; } </style>

    <script src="//unpkg.com/force-graph"></script>
    <!--<script src="../../dist/force-graph.js"></script>-->
</head>

<body>
<div id="graph"></div>

<script type="text/javascript" src="../data/data.js"></script>
<script>
  let i, s, N = data["nodes"].length, E = data["links"].length;
  let g = {
    nodes: [],
    edges: []
  };
  let h = {}; // Hash table, IP/domain->id

  for (let i = 0; i < N; i++)
  {
    let node = data['nodes'][i]
    h[node['id']] = i.toString();
    g.nodes.push({
      id: i.toString(),
      label: node["id"],
      x: Math.random(),
      y: Math.random(),
      size: 1,
      color: (node["group"] == '0' ? '#ff0000' : '#0099ee')
    })
  }


  for (let i = 0; i < E; i++)
  {
    let edge = data['links'][i]
    g.edges.push({
      id: i.toString(),
      source: h[edge["source"]],
      target: h[edge["target"]],
      color: '#666'
    })
  }

  // Random tree
  const gData = {
    nodes: g.nodes,
    links: g.edges
  };

  const Graph = ForceGraph()
  (document.getElementById('graph'))
    .linkDirectionalParticles(2)
    .graphData(gData);
</script>
</body>
```

`data.js`` defines a JSON graph with ~5000 nodes and ~5000 edges. As it contains confidential information, I cannot share it in current form.

**Comment by vasturiano** [comment]
Thanks for reaching out @hsluoyz.

It's difficult to say for sure without a reproducible example, but it may be related to your pre-setting of the `x,y` coordinates here:
```
x: Math.random(),
y: Math.random(),
```

This is basically compressing all the 5000 elements within the space of a single pixel. The result is that when the force simulation kicks in, it generates a big bang pushing out the nodes very far. Depending on how far they get pushed, the remaining force cooldown period may not be enough to bring the nodes back to the center, and you freeze into a layout that is too scattered.

Could you please try without setting the node coordinates (they get automatically pre-positioned in phylotaxis figure), and see if it solves the issue?
