### ISSUE TITLE
Use .svg instead of .jpg or .png in images as nodes force graph

### ISSUE THREAD

**Issue by cstark9** [vasturiano/force-graph#68]
**Is your feature request related to a problem? Please describe.**
Trying to use the _images as nodes_ force graph and trying to use .svg(s) for the images, however the images won't show up on the canvas. I have tried to convert them to .png and have the same issue. If i use a .png it works, however, I need to use .svgs since they are icons previously used in another part of my project, and must stay as .svg. Also- is there a way to provide a color if you use an image? If I used an icon that was round like a node and had an image on it, is there a way to provide a color for it, so I can continue to color my nodes on the fly?

**Describe the solution you'd like**
I would like to be able to use .svg(s) for images and have a way to provide a color (similar to your 3d library).

**Describe alternatives you've considered**
I have tried to convert .svg to .png and still having an issue rendering on the canvas. Cannot see a way to color the image either. 
Alternatively, another option could be added to the .nodeCanvasObject() to attach an icon (that allows .svg)

**Comment by vasturiano** [comment]
@cstark9 the current [images as nodes example](https://vasturiano.github.io/force-graph/example/img-nodes/) supports `.svg` files fine, as long as they're well formed and include the required styling for rendering.
I would double check your `.css` file. If you open it in the browser or an image editor does it render correctly?

**Comment by cstark9** [comment]
@vasturiano  - Thanks for the fast reply!
hmm--  I can open the .svg in IE and it displays fine- 
example: 
![image](https://user-images.githubusercontent.com/56411756/66616085-00590800-eb95-11e9-99a8-50d40fcca46e.png)

The html for the .svg is this:
```
<svg id="Building" viewBox="0 0 128 128" width="128" height="128" xmlns="http://www.w3.org/2000/svg">
  <defs><style>.cls-1{fill:#fff;}</style></defs>
  <title>Building</title>
  <ellipse ry="60" rx="60" id="svg_1" cy="64" cx="64" stroke-width="1.5" class="cls-1"/>
  <g stroke="null" id="svg_26">
   <rect stroke="null" id="svg_3" height="40.276281" width="27.240023" y="53.409512" x="34.700802" stroke-opacity="null" stroke-width="1.5" fill="#000000"/>
   <rect stroke="null" id="svg_4" height="65.557799" width="30.487894" y="28.295394" x="65.686212" stroke-opacity="null" stroke-width="1.5" fill="#000000"/>
   <rect stroke="null" id="svg_5" height="7.365604" width="79.180238" y="89.935488" x="25.393484" stroke-width="1.5" fill="#000000"/>
   <rect stroke="null" id="svg_7" height="6.885238" width="4.26229" y="58.003591" x="39.983632" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_8" height="7.030804" width="4.370884" y="58.631672" x="46.071126" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_9" height="7.030804" width="4.370884" y="40.552462" x="70.615319" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_10" height="7.030804" width="4.370884" y="68.012053" x="39.010468" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_11" height="7.030804" width="4.370884" y="58.631672" x="39.010468" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_12" height="7.030804" width="4.370884" y="68.012053" x="46.071126" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_13" height="7.030804" width="4.370884" y="77.243375" x="39.010468" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_14" height="7.030804" width="4.370884" y="77.243375" x="46.073127" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_15" height="7.030804" width="4.370884" y="77.243375" x="52.967724" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_16" height="7.030804" width="4.370884" y="40.552462" x="78.896463" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_17" height="7.030804" width="4.370884" y="40.552462" x="86.600007" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_18" height="7.030804" width="4.370884" y="50.952846" x="70.615319" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_19" height="7.030804" width="4.370884" y="61.316147" x="70.615319" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_20" height="7.030804" width="4.370884" y="50.931267" x="78.896463" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_21" height="7.030804" width="4.370884" y="61.494074" x="86.431896" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_22" height="3.850203" width="4.370884" y="33.354258" x="70.615319" fill-opacity="null" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_24" height="3.850203" width="4.370884" y="33.354258" x="78.684643" fill-opacity="null" stroke-width="1.5" class="cls-1"/>
   <rect stroke="null" id="svg_25" height="3.850203" width="4.370884" y="33.354258" x="86.585855" fill-opacity="null" stroke-width="1.5" class="cls-1"/>
  </g>
</svg>
``` 
* Note- the circle is white because that's the default color on a black background. 

I have a function that then handles assigning the image to the particular node, and and then do the ```context.drawImage``` and pass in my node image.
If I log out my image the image path looks correct, and I can double click on it in the _Network_ tab of my developer tools and it opens the image fine- but I also get a 304. Maybe I'm missing something else?

**Comment by cstark9** [comment]
tried it in FF instead of chrome--- I see the images there (but they are all stacked on top of each other- as the icons come in, I can see them all though...) but it won't render in Chrome.

**Comment by vasturiano** [comment]
@cstark9 I've just made a small example with your svg image in `force-graph`. Seems to work fine: https://codesandbox.io/s/force-graph-svg-images-5zbkp

Does it not work for you in Chrome?

**Comment by cstark9** [comment]
Thanks for the example- It still does not work for me in Chrome- but it works perfectly in FF. I still get the 304- tried clearing my cache, history, view in incognito, etc, and still the same. Network shows my preview perfectly, but nothing renders on the canvas. Not sure why it would work in FF and not Chrome.

Is there a way to add change the image color with context.drawImage?

**Comment by vasturiano** [comment]
`drawImage` just renders the image onto the canvas. I don't think you can use it to alter any styling. The color should be specified in the `svg` file itself.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

**Comment by cstark9** [comment]
@vasturiano  - I have a default color in each svg, but wanted to be able to change the color as they rendered, so I could use a function to determine what color the node should be in certain circumstances. I think I'm definitely doing something that isn't expected of an image on a canvas.
