### ISSUE TITLE
Graph density

### ISSUE THREAD

**Issue by joshhopkins** [vasturiano/force-graph#69]
Nice library! Is there currently any way of controlling the density of a graph(s) / space between nodes? Having control over the arrangement would be great.

**Comment by vasturiano** [comment]
@joshhopkins there's multiple ways you can control that.

One easy way you can try is to adjust the inertia of the medium using `.d3VelocityDecay(<num>)`. This determines how much the nodes are slowed down by the space.

Other ways include calibrating the forces that are in effect in the system, like the link distance (via `.d3Force('link').distance(link => ...)`) or the natural repulsion force of all the nodes (`.d3Force('charge').strength(node => ...)`).

The docs at https://github.com/d3/d3-force are very helpful for guiding with this calibration.
