### ISSUE TITLE
Apply curvature in link texts

### ISSUE THREAD

**Issue by ravik3592** [vasturiano/force-graph#70]
I have applied curvature in link, which works perfect.
How to apply curvature to link texts based on curvature value?

**Comment by vasturiano** [comment]
@ravik3592 to the extent of my knowledge there's no built-in way to draw a text along a curve in HTML5 canvas. But you could possibly use a third-party convenience lib for that, for example: https://github.com/Viglino/Canvas-TextPath

You would use this in your `linkCanvasObject` method and have it follow a bezier curve between the two nodes.
