### ISSUE TITLE
wheel event deltaX and deltaY values not accurate

### ISSUE THREAD

**Issue by SZBoatwright** [vasturiano/force-graph#76]
**Describe the bug**
Wheel events on the canvas element are not passing correct deltaX/deltaY values. I've tested to make sure this is specific to the canvas added by this library by adding a wheel event to my document body that gives correct deltaX/deltaY values until I hover over the canvas, and then the values are no longer correct.

All delta values are being attributed to deltaX. So it doesn't matter if I scroll horizontally or vertically, it's always the deltaX value that shows the change. This is causing me issues, as I'm trying to add a feature to my graph to enable panning instead of zooming when shift is held down while scrolling.

**To Reproduce**
1. Create a new forcegraph
2. Add wheel event to document body:
```
document.addEventListener('wheel', event => {
  console.log(event.deltaX, event.deltaY);
})
```
3. When scrolling, notice how the deltaX and deltaY values are correct when not focused on the graph, but are no longer accurate when the graph is the active element.

**Expected behavior**
I would expect deltaX and deltaY to be their correct values

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
- Brave v 0.69.135

**Additional context**
There also seems to be some odd behavior where the wheel event doesn't even fire on the canvas unless the shift key is held down. Not sure why that's happening, but I would expect to be able to have a wheel event happen no matter if I'm holding shift or not. It isn't currently hurting me as of now since I only care about the event when I'm holding shift, but maybe that's linked to the issue I'm having?

**Comment by vasturiano** [comment]
@SZBoatwright thanks for reaching out. 

Could this be a particularity of [d3-zoom](https://github.com/d3/d3-zoom)?
Can you reproduce your issue in the examples on that module?

**Comment by SZBoatwright** [comment]
Actually, I've looked into this a bit more, and it looks like it might be default browser behavior. Holding shift while scrolling will cause the deltaY value to instead apply as deltaX. 

example: https://codepen.io/SZBoatwright/pen/poodZWg?editors=0011

**Comment by vasturiano** [comment]
Yep, it may be be pointer device specific. I can't reproduce it in your codepen using a trackpad.
