### ISSUE TITLE
Add d3-force-reuse support

### ISSUE THREAD

**Issue by shreyasnagare** [vasturiano/force-graph#77]
Is there a chance we can use d3-force-reuse plugin instead of d3-force? It claims to reduce the computation time by 10% to 90% ([source](https://www.twosixlabs.com/faster-force-directed-graph-layouts-by-reusing-force-approximations/)).

**Comment by vasturiano** [comment]
@shreyasnagare thanks for the suggestion.
You can easily swap that externally by changing the `charge` force:
```
myGraph.d3Force('charge', forceManyBodyReuse());
```

The reuse plugin is more performant, but the layout is also less optimal. So I prefer not to change it internally and give users the choice to swap.
