### ISSUE TITLE
Node render order needed to minimize label overlaps

### ISSUE THREAD

**Issue by invisig0th** [vasturiano/force-graph#78]
Since an HTML canvas has no z-index controls, we need a way to specify node render order to allow selected/labeled nodes to render on top.

![optic-overlap](https://user-images.githubusercontent.com/2624245/69013585-954ae000-094f-11ea-9334-bf131d201b46.png)

Seems like this could be controlled within paintNodes.  I'd be happy to take a shot at it if that would be simplest.

**Comment by vasturiano** [comment]
@invisig0th you can specify node render order by sorting your input array in `graphData.nodes`. The canvas renderer should respect that order when drawing the nodes.

**Comment by invisig0th** [comment]
Gotcha.  Probably better to re-sort on selection changes than to re-sort on draw. Thanks!

**Comment by 0xroko** [comment]
In my case sorting didn't help (selected nodes were close together), so I created new canvas "above" the force graph canvas, just for the labels. And replaced `ctx` with `labelCtx`.
