### ISSUE TITLE
Avoid lines and nodes overlapping

### ISSUE THREAD

**Issue by ravik3592** [vasturiano/force-graph#79]
I tried to draw with 300 nodes and 500 edges but my graph looks clumsy. Is there any option to make it look good
![Capture](https://user-images.githubusercontent.com/56120798/70887247-6afa4a00-2003-11ea-949d-431976647c1f.PNG)

**Comment by vasturiano** [comment]
@ravik3592 there's multiple ways you can optimize the layout. I would suggest letting the force engine run for longer time, using `cooldownTime`. Also, you can try calibrating the forces in action in the system using `d3Force`. For example, to apply a stronger repelling force between the nodes:
```
myGraph.d3Force('charge').strength(-100);
```

**Comment by ravik3592** [comment]
@vasturiano I tried setting this. 
![capture222](https://user-images.githubusercontent.com/56120798/70969056-f980d100-20c0-11ea-96c5-258e7ce200cf.PNG)


Node distance increased but still i cant prevent overlapping issue.
 Im expecting similar to the below attachment
![Capture11](https://user-images.githubusercontent.com/56120798/70968952-a870dd00-20c0-11ea-8f98-71c6a3d53768.PNG) 
or this one
https://observablehq.com/@d3/force-directed-graph

**Comment by vasturiano** [comment]
@ravik3592 the force-directed-graph example yields the same result as this library. It's using the same force directed layout, as you can see here: https://vasturiano.github.io/force-graph/example/load-json/

It's the difference in the data that poses the difficulty in separating the items. 

The dendrogram image you posted is not a force-directed layout, but a hierarchical one: https://github.com/d3/d3-hierarchy#cluster

That's only applicable to acyclical datasets. If that's your case you can also try switching to `dagMode`, as in this example: https://vasturiano.github.io/force-graph/example/tree/

**Comment by ravik3592** [comment]
@vasturiano I tried with dagmode, it helped me fix the node overlapping in  graph with few nodes.
But i am facing cyclic error. Is it possible to allow cyclic connectors in dag mode also. This worked without dagmode
![Capture](https://user-images.githubusercontent.com/56120798/70997867-f1925280-20fb-11ea-9cb3-7b70bab0bc99.PNG)

**Comment by vasturiano** [comment]
@ravik3592 DAG (Directed Acyclic Graph) mode can only work with acyclic data sets. If that's a possibility, you can try sanitizing your dataset to remove cycle links before feeding it to the graph.
