### ISSUE TITLE
Error when node not found

### ISSUE THREAD

**Issue by ravik3592** [vasturiano/force-graph#80]
I am getting random data from db. there may be few nodes missing. Is it possible to add try catch to handle error. I did this to make my graph work
 function h(r) {
			try {
            for (var o = 0, u = t.length; o < c; ++o)
                for (var s, l, h, f, p, d = 0, v = 0, y = 0, g = 0; d < u; ++d) 
					l = (s = t[d]).source, v = (h = s.target).x + h.vx - l.x - l.vx || Ni(), i > 1 && (y = h.y + h.vy - l.y - l.vy || Ni()), i > 2 && (g = h.z + h.vz - l.z - l.vz || Ni()), v *= f = ((f = Math.sqrt(v * v + y * y + g * g)) - e[d]) / f * r * n[d], y *= f, g *= f, h.vx -= v * (p = a[d]), i > 1 && (h.vy -= y * p), i > 2 && (h.vz -= g * p), l.vx += v * (p = 1 - p), i > 1 && (l.vy += y * p), i > 2 && (l.vz += g * p)
			} catch(e) {
			}
		}

**Comment by vasturiano** [comment]
@ravik3592 an exception is thrown by the module if one of the links references a non-existing node. This is intentional to prevent broken links from being rendered.
It's important to clean up your dataset before feeding it to the component so that these errors don't occur.
