### ISSUE TITLE
View Coordinates

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/force-graph#87]
**Is your feature request related to a problem? Please describe.**
I am putting tooltips that appear when clicking on a node, currently they appear using the event x and y value of the onNodeClick to position themselves. 

As with this they are separate from the graph and static so they do not move when zooming, panning, or dragging a node. 

I am wanting to close the tooltips and have them re-open with onNodeDragEnd, after a zoom, and when panning ends. I can get this functionality myself with a bit of code, but I do not have a correct location for them to position themselves at because I no longer have an event with an X,Y. 

**Describe the solution you'd like**
Having a viewCoordinate showing it's position in the canvas, component, or even the window for each node would allow me to reference the node and reopen the tooltip using those coordinates.

That may use too much processing to add it to each node, so maybe just a converter function like myGraph.viewCoordinates that converts any given graph x,y coordinates to canvas, component, or window coordinates.

**Describe alternatives you've considered**
I have tried using the change in x and y coming back from onZoom, but I was having some problems with the correct positioning.

Maybe there is already a function like this somewhere in the underlying d3 that converts this? I was unable to find that though.

I am also using your 3D version of force graph alongside this, so this converter there would be helpful. It also has no onZoom (or pan) for me to hook into there though.

Thanks for your time!

**Comment by vasturiano** [comment]
@Alexithemia thanks for your request. I think it would be useful indeed to have the translation convenience utility. Let me try to add them (forward and reverse translation method) when I have a bit of time. 👍 

As for the 3D mode the navigation method is quite different, since it's based on moving a camera POV through the 3D space. So I'm not sure how easy it would be to perform the same translation. Also, it would only be possible to translate from the 3D frustum to screen coords, not the reverse.

**Comment by Alexithemia** [comment]
While having both in 3D would be nice, I only need to screen coords. Thanks!

**Comment by vasturiano** [comment]
@Alexithemia I've added two methods that allow you to convert between viewport and graph coordinates: `screen2GraphCoords(x, y)` and `graph2ScreenCoords(x, y)`.
Please use the latest version: `1.23.0`.
