### ISSUE TITLE
Highlight nodes by changing their color or centering the graph on them.

### ISSUE THREAD

**Issue by pournaki** [vasturiano/force-graph#88]
I am working on an interface in which you can search for a node in the visualized network. I am thinking of different ways to achieve this: You could for instance change a node's color if, say his "label"-key, matches an input-form value. Or you could zoom in on the node that matches that value. 

Therefore, I wonder if it is possible to access/change a specific node's color after the graph has rendered. 

And also, if is it possible to access a specific node's x-y coordinates to feed them into the centerAt-command.

Thanks a lot for your work!

**Comment by Alexithemia** [comment]
For this graph, it is using canvas. So it is constantly re-drawing.

So you could either give the node a value and have it go through .nodeColor(node => node.color) then any time you change that value in the node object it would change on the next draw, which is nearly instantly. But you would have to access that node again to remove or change it back, which could take some extra processing you don't want to do.

My preferred way is to have a global variable called something like selectedNode that is just a node's ID. Then do things like .nodeColor(node => if (node.id === selectedNode) return "red")

For the centering you just have to grab the node.  .onNodeClick provides the node itself back that you can use the x and y from then just graph.centerAt(node.x, node.y, 500).
If you need to access the node from some outside location, you just need to get it from the data location you fed into the graph. The graph actually uses and edits that data source.
Ex.
```
const data = {
  nodes: [ ... ],
  links: [ ... ]
}
myGraph.graphData(data);

const getNode = id => {
  return data.nodes.find(node => node.id === id);
}
```
With this example using getNode(id) would get you the node object with all the data the graph has added to it, including it's current x and y to feed into .centerAt

**Comment by pournaki** [comment]
Thanks a lot for your help, it is exactly what I was looking for!

**Comment by pournaki** [comment]
I have one more question in the context of changing node colors. I now want to create a funtion to recolor the nodes using `nodeAutoColorBy({arg})`, where {arg} is the value of a selectbox (and a key of the node dict). However, when I run `Graph.nodeAutoColorBy({arg})`, the nodes all move a little bit, but their color does not change. Is there a way to toggle the `nodeAutoColorBy` function?
