### ISSUE TITLE
onZoom - panning

### ISSUE THREAD

**Issue by Alexithemia** [vasturiano/force-graph#89]
Thanks again for your quick help with the coordinate translation! Hope you can implement the one way method on the 3D version when you have time.

**Is your feature request related to a problem? Please describe.**
The onZoom method, continuously fires while panning, I would like to only fire something once the panning ends though.

**Describe the solution you'd like**
I could of course do this with some debouncing, but you do have other on end methods like onNodeDrag end etc. I was wondering if you could add one for onZoom end? Or separate onPan and have onPanEnd as well? Either would work great.

**Describe alternatives you've considered**
Currently just using onZoom, works fine depending on how much I'm making it do, but can slow down a lot as it constantly runs while I am panning.

Thanks for your time.

**Comment by vasturiano** [comment]
Thanks for the request @Alexithemia, and @veryspry for the PR! 

`onZoomEnd` now available on `v1.24.0`. 🎉
