### ISSUE TITLE
d3.forceCollide not working in angular

### ISSUE THREAD

**Issue by ravik3592** [vasturiano/force-graph#91]
Im trying to use d3.forceCollide but i get d3 not defined error
my code :
import d3 from './../../../assets/plugins/force-graph/d3-force.min.js';
import ForceGraph from './../../../../../../src/assets/plugins/force-graph/force-graph.js';
 Graph
          .graphData(gData)
          .d3Force('collide', d3.forceCollide(13))

**Comment by Alexithemia** [comment]
Not sure why you are specifying the entire filepath, you should just be npm installing these into your project. But you are not going to want to use the d3-force.min from inside of the force graph, you are going to want to include the actual d3-force library https://github.com/d3/d3-force.

You are also going to want to use
```
import * as d3 from 'd3-force'
```

You could try using import * as d3 from './../../../assets/plugins/force-graph/d3-force.min.js'; But I can't say for sure it will work.

**Comment by ravik3592** [comment]
yes its working now..
