### ISSUE TITLE
Animation stops after onNodeHover()

### ISSUE THREAD

**Issue by pournaki** [vasturiano/force-graph#97]
This might not be a bug but rather a misunderstanding of the onNodeHover function. 
I want to perform a certain action when hovering over a node (while keeping the standard functionality of showing the label of the node on hover).
This is a minimal example of my code:
```
Graph.onNodeHover((node => {
console.log(node.id) 
}))
```
However, when I do this, the graph animation stops after I move the mouse away from the node.
What am I missing? 

Thank you very much!

**Comment by vasturiano** [comment]
@pournaki thanks for reaching out.

When hovering out of the node `onNodeHover` is invoked with a `null` value. This causes an error  in your code as you try to read the property `id` of `null`.

If you just want the console log to trigger on hover in you can add a protection like:
```
Graph.onNodeHover(node => node && console.log(node.id))
```

**Comment by pournaki** [comment]
@vasturiano thanks for the fast answer! 

> When hovering out of the node onNodeHover is invoked with a null value. This causes an error in your code as you try to read the property id of null.

Got it!
> If you just want the console log to trigger on hover in you can add a protection like:
> ```Graph.onNodeHover(node` => node && `console.log(node.id))```

This works perfectly, thank you.
