### ISSUE TITLE
linkDirectionalParticleColor does not change color of particle

### ISSUE THREAD

**Issue by maximegheraille** [vasturiano/force-graph#98]
**Describe the bug**
when sitting the parameter .linkDirectionalParticleColor('red'), it does not change the color of the particle       

**To Reproduce**
1. use the directional-links-particile index
2. set .linkDirectionalParticleColor('red')

**Expected behavior**
the particle should be red

**Screenshots**

![image](https://user-images.githubusercontent.com/32335849/75336548-a4fd8d00-588b-11ea-9475-b3e69ae49013.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by vasturiano** [comment]
@maximegheraille that method takes an accessor function, or a link attribute name. You should do
 ```
.linkDirectionalParticleColor(() => 'red')
```

**Comment by maximegheraille** [comment]
> @maximegheraille that method takes an accessor function, or a link attribute name. You should do
> 
> ```
> .linkDirectionalParticleColor(() => 'red')
> ```

perfect it worked, thank you
